#pragma once
enum class ABILITY_TYPES : unsigned long
{
	ABILITY_TYPE_BASIC = 0,
	ABILITY_TYPE_ULTIMATE = 1,
	ABILITY_TYPE_ATTRIBUTES = 2,
	ABILITY_TYPE_HIDDEN = 3,
};

enum class AbilityLearnResult_t : unsigned long
{
	ABILITY_CAN_BE_UPGRADED = 0,
	ABILITY_CANNOT_BE_UPGRADED_NOT_UPGRADABLE = 1,
	ABILITY_CANNOT_BE_UPGRADED_AT_MAX = 2,
	ABILITY_CANNOT_BE_UPGRADED_REQUIRES_LEVEL = 3,
	ABILITY_NOT_LEARNABLE = 4,
};

enum class AnimationProcessingType_t : unsigned long
{
	ANIMATION_PROCESSING_SERVER_SIMULATION = 0,
	ANIMATION_PROCESSING_CLIENT_SIMULATION = 1,
	ANIMATION_PROCESSING_CLIENT_PREDICTION = 2,
	ANIMATION_PROCESSING_CLIENT_INTERPOLATION = 3,
	ANIMATION_PROCESSING_CLIENT_RENDER = 4,
	ANIMATION_PROCESSING_MAX = 5,
};

enum class AnimationSnapshotType_t : unsigned long
{
	ANIMATION_SNAPSHOT_SERVER_SIMULATION = 0,
	ANIMATION_SNAPSHOT_CLIENT_SIMULATION = 1,
	ANIMATION_SNAPSHOT_CLIENT_PREDICTION = 2,
	ANIMATION_SNAPSHOT_CLIENT_INTERPOLATION = 3,
	ANIMATION_SNAPSHOT_CLIENT_RENDER = 4,
	ANIMATION_SNAPSHOT_FINAL_COMPOSITE = 5,
	ANIMATION_SNAPSHOT_MAX = 6,
};

enum class AttachmentInfluenceFlags_t : unsigned long
{
	ATTACHMENT_INFLUENCE_FLAGS_NONE = 0,
	ATTACHMENT_INFLUENCE_FLAGS_ROOT_TRANSFORM = 1,
};

enum class Attributes : signed long
{
	DOTA_ATTRIBUTE_STRENGTH = 0,
	DOTA_ATTRIBUTE_AGILITY = 1,
	DOTA_ATTRIBUTE_INTELLECT = 2,
	DOTA_ATTRIBUTE_MAX = 3,
	DOTA_ATTRIBUTE_INVALID = -1,
};

enum class BaseActivity_t : unsigned long
{
	ACT_RESET = 0,
	ACT_IDLE = 1,
	ACT_TRANSITION = 2,
	ACT_COVER = 3,
	ACT_COVER_MED = 4,
	ACT_COVER_LOW = 5,
	ACT_WALK = 6,
	ACT_WALK_AIM = 7,
	ACT_WALK_CROUCH = 8,
	ACT_WALK_CROUCH_AIM = 9,
	ACT_RUN = 10,
	ACT_RUN_AIM = 11,
	ACT_RUN_CROUCH = 12,
	ACT_RUN_CROUCH_AIM = 13,
	ACT_RUN_PROTECTED = 14,
	ACT_SCRIPT_CUSTOM_MOVE = 15,
	ACT_RANGE_ATTACK1 = 16,
	ACT_RANGE_ATTACK2 = 17,
	ACT_RANGE_ATTACK1_LOW = 18,
	ACT_RANGE_ATTACK2_LOW = 19,
	ACT_DIESIMPLE = 20,
	ACT_DIEBACKWARD = 21,
	ACT_DIEFORWARD = 22,
	ACT_DIEVIOLENT = 23,
	ACT_DIERAGDOLL = 24,
	ACT_FLY = 25,
	ACT_HOVER = 26,
	ACT_GLIDE = 27,
	ACT_SWIM = 28,
	ACT_JUMP = 29,
	ACT_HOP = 30,
	ACT_LEAP = 31,
	ACT_LAND = 32,
	ACT_CLIMB_UP = 33,
	ACT_CLIMB_DOWN = 34,
	ACT_CLIMB_DISMOUNT = 35,
	ACT_SHIPLADDER_UP = 36,
	ACT_SHIPLADDER_DOWN = 37,
	ACT_STRAFE_LEFT = 38,
	ACT_STRAFE_RIGHT = 39,
	ACT_ROLL_LEFT = 40,
	ACT_ROLL_RIGHT = 41,
	ACT_TURN_LEFT = 42,
	ACT_TURN_RIGHT = 43,
	ACT_CROUCH = 44,
	ACT_CROUCHIDLE = 45,
	ACT_STAND = 46,
	ACT_USE = 47,
	ACT_ALIEN_BURROW_IDLE = 48,
	ACT_ALIEN_BURROW_OUT = 49,
	ACT_SIGNAL1 = 50,
	ACT_SIGNAL2 = 51,
	ACT_SIGNAL3 = 52,
	ACT_SIGNAL_ADVANCE = 53,
	ACT_SIGNAL_FORWARD = 54,
	ACT_SIGNAL_GROUP = 55,
	ACT_SIGNAL_HALT = 56,
	ACT_SIGNAL_LEFT = 57,
	ACT_SIGNAL_RIGHT = 58,
	ACT_SIGNAL_TAKECOVER = 59,
	ACT_LOOKBACK_RIGHT = 60,
	ACT_LOOKBACK_LEFT = 61,
	ACT_COWER = 62,
	ACT_SMALL_FLINCH = 63,
	ACT_BIG_FLINCH = 64,
	ACT_MELEE_ATTACK1 = 65,
	ACT_MELEE_ATTACK2 = 66,
	ACT_RELOAD = 67,
	ACT_RELOAD_START = 68,
	ACT_RELOAD_FINISH = 69,
	ACT_RELOAD_LOW = 70,
	ACT_ARM = 71,
	ACT_DISARM = 72,
	ACT_DROP_WEAPON = 73,
	ACT_DROP_WEAPON_SHOTGUN = 74,
	ACT_PICKUP_GROUND = 75,
	ACT_PICKUP_RACK = 76,
	ACT_IDLE_ANGRY = 77,
	ACT_IDLE_RELAXED = 78,
	ACT_IDLE_STIMULATED = 79,
	ACT_IDLE_AGITATED = 80,
	ACT_IDLE_STEALTH = 81,
	ACT_IDLE_HURT = 82,
	ACT_WALK_RELAXED = 83,
	ACT_WALK_STIMULATED = 84,
	ACT_WALK_AGITATED = 85,
	ACT_WALK_STEALTH = 86,
	ACT_RUN_RELAXED = 87,
	ACT_RUN_STIMULATED = 88,
	ACT_RUN_AGITATED = 89,
	ACT_RUN_STEALTH = 90,
	ACT_IDLE_AIM_RELAXED = 91,
	ACT_IDLE_AIM_STIMULATED = 92,
	ACT_IDLE_AIM_AGITATED = 93,
	ACT_IDLE_AIM_STEALTH = 94,
	ACT_WALK_AIM_RELAXED = 95,
	ACT_WALK_AIM_STIMULATED = 96,
	ACT_WALK_AIM_AGITATED = 97,
	ACT_WALK_AIM_STEALTH = 98,
	ACT_RUN_AIM_RELAXED = 99,
	ACT_RUN_AIM_STIMULATED = 100,
	ACT_RUN_AIM_AGITATED = 101,
	ACT_RUN_AIM_STEALTH = 102,
	ACT_CROUCHIDLE_STIMULATED = 103,
	ACT_CROUCHIDLE_AIM_STIMULATED = 104,
	ACT_CROUCHIDLE_AGITATED = 105,
	ACT_WALK_HURT = 106,
	ACT_RUN_HURT = 107,
	ACT_SPECIAL_ATTACK1 = 108,
	ACT_SPECIAL_ATTACK2 = 109,
	ACT_COMBAT_IDLE = 110,
	ACT_WALK_SCARED = 111,
	ACT_RUN_SCARED = 112,
	ACT_VICTORY_DANCE = 113,
	ACT_DIE_HEADSHOT = 114,
	ACT_DIE_CHESTSHOT = 115,
	ACT_DIE_GUTSHOT = 116,
	ACT_DIE_BACKSHOT = 117,
	ACT_FLINCH_HEAD = 118,
	ACT_FLINCH_CHEST = 119,
	ACT_FLINCH_STOMACH = 120,
	ACT_FLINCH_LEFTARM = 121,
	ACT_FLINCH_RIGHTARM = 122,
	ACT_FLINCH_LEFTLEG = 123,
	ACT_FLINCH_RIGHTLEG = 124,
	ACT_FLINCH_PHYSICS = 125,
	ACT_FLINCH_HEAD_BACK = 126,
	ACT_FLINCH_CHEST_BACK = 127,
	ACT_FLINCH_STOMACH_BACK = 128,
	ACT_FLINCH_CROUCH_FRONT = 129,
	ACT_FLINCH_CROUCH_BACK = 130,
	ACT_FLINCH_CROUCH_LEFT = 131,
	ACT_FLINCH_CROUCH_RIGHT = 132,
	ACT_IDLE_ON_FIRE = 133,
	ACT_WALK_ON_FIRE = 134,
	ACT_RUN_ON_FIRE = 135,
	ACT_RAPPEL_LOOP = 136,
	ACT_180_LEFT = 137,
	ACT_180_RIGHT = 138,
	ACT_90_LEFT = 139,
	ACT_90_RIGHT = 140,
	ACT_STEP_LEFT = 141,
	ACT_STEP_RIGHT = 142,
	ACT_STEP_BACK = 143,
	ACT_STEP_FORE = 144,
	ACT_GESTURE_RANGE_ATTACK1 = 145,
	ACT_GESTURE_RANGE_ATTACK2 = 146,
	ACT_GESTURE_MELEE_ATTACK1 = 147,
	ACT_GESTURE_MELEE_ATTACK2 = 148,
	ACT_GESTURE_RANGE_ATTACK1_LOW = 149,
	ACT_GESTURE_RANGE_ATTACK2_LOW = 150,
	ACT_MELEE_ATTACK_SWING_GESTURE = 151,
	ACT_GESTURE_SMALL_FLINCH = 152,
	ACT_GESTURE_BIG_FLINCH = 153,
	ACT_GESTURE_FLINCH_BLAST = 154,
	ACT_GESTURE_FLINCH_BLAST_SHOTGUN = 155,
	ACT_GESTURE_FLINCH_BLAST_DAMAGED = 156,
	ACT_GESTURE_FLINCH_BLAST_DAMAGED_SHOTGUN = 157,
	ACT_GESTURE_FLINCH_HEAD = 158,
	ACT_GESTURE_FLINCH_CHEST = 159,
	ACT_GESTURE_FLINCH_STOMACH = 160,
	ACT_GESTURE_FLINCH_LEFTARM = 161,
	ACT_GESTURE_FLINCH_RIGHTARM = 162,
	ACT_GESTURE_FLINCH_LEFTLEG = 163,
	ACT_GESTURE_FLINCH_RIGHTLEG = 164,
	ACT_GESTURE_TURN_LEFT = 165,
	ACT_GESTURE_TURN_RIGHT = 166,
	ACT_GESTURE_TURN_LEFT45 = 167,
	ACT_GESTURE_TURN_RIGHT45 = 168,
	ACT_GESTURE_TURN_LEFT90 = 169,
	ACT_GESTURE_TURN_RIGHT90 = 170,
	ACT_GESTURE_TURN_LEFT45_FLAT = 171,
	ACT_GESTURE_TURN_RIGHT45_FLAT = 172,
	ACT_GESTURE_TURN_LEFT90_FLAT = 173,
	ACT_GESTURE_TURN_RIGHT90_FLAT = 174,
	ACT_BARNACLE_HIT = 175,
	ACT_BARNACLE_PULL = 176,
	ACT_BARNACLE_CHOMP = 177,
	ACT_BARNACLE_CHEW = 178,
	ACT_DO_NOT_DISTURB = 179,
	ACT_SPECIFIC_SEQUENCE = 180,
	ACT_VM_DEPLOY = 181,
	ACT_VM_RELOAD_EMPTY = 182,
	ACT_VM_DRAW = 183,
	ACT_VM_HOLSTER = 184,
	ACT_VM_IDLE = 185,
	ACT_VM_FIDGET = 186,
	ACT_VM_PULLBACK = 187,
	ACT_VM_PULLBACK_HIGH = 188,
	ACT_VM_PULLBACK_LOW = 189,
	ACT_VM_THROW = 190,
	ACT_VM_DROP = 191,
	ACT_VM_PULLPIN = 192,
	ACT_VM_PRIMARYATTACK = 193,
	ACT_VM_SECONDARYATTACK = 194,
	ACT_VM_RELOAD = 195,
	ACT_VM_DRYFIRE = 196,
	ACT_VM_HITLEFT = 197,
	ACT_VM_HITLEFT2 = 198,
	ACT_VM_HITRIGHT = 199,
	ACT_VM_HITRIGHT2 = 200,
	ACT_VM_HITCENTER = 201,
	ACT_VM_HITCENTER2 = 202,
	ACT_VM_MISSLEFT = 203,
	ACT_VM_MISSLEFT2 = 204,
	ACT_VM_MISSRIGHT = 205,
	ACT_VM_MISSRIGHT2 = 206,
	ACT_VM_MISSCENTER = 207,
	ACT_VM_MISSCENTER2 = 208,
	ACT_VM_HAULBACK = 209,
	ACT_VM_SWINGHARD = 210,
	ACT_VM_SWINGMISS = 211,
	ACT_VM_SWINGHIT = 212,
	ACT_VM_IDLE_TO_LOWERED = 213,
	ACT_VM_IDLE_LOWERED = 214,
	ACT_VM_LOWERED_TO_IDLE = 215,
	ACT_VM_RECOIL1 = 216,
	ACT_VM_RECOIL2 = 217,
	ACT_VM_RECOIL3 = 218,
	ACT_VM_PICKUP = 219,
	ACT_VM_RELEASE = 220,
	ACT_VM_MAUL_LOOP = 221,
	ACT_VM_ATTACH_SILENCER = 222,
	ACT_VM_DETACH_SILENCER = 223,
	ACT_SLAM_STICKWALL_IDLE = 224,
	ACT_SLAM_STICKWALL_ND_IDLE = 225,
	ACT_SLAM_STICKWALL_ATTACH = 226,
	ACT_SLAM_STICKWALL_ATTACH2 = 227,
	ACT_SLAM_STICKWALL_ND_ATTACH = 228,
	ACT_SLAM_STICKWALL_ND_ATTACH2 = 229,
	ACT_SLAM_STICKWALL_DETONATE = 230,
	ACT_SLAM_STICKWALL_DETONATOR_HOLSTER = 231,
	ACT_SLAM_STICKWALL_DRAW = 232,
	ACT_SLAM_STICKWALL_ND_DRAW = 233,
	ACT_SLAM_STICKWALL_TO_THROW = 234,
	ACT_SLAM_STICKWALL_TO_THROW_ND = 235,
	ACT_SLAM_STICKWALL_TO_TRIPMINE_ND = 236,
	ACT_SLAM_THROW_IDLE = 237,
	ACT_SLAM_THROW_ND_IDLE = 238,
	ACT_SLAM_THROW_THROW = 239,
	ACT_SLAM_THROW_THROW2 = 240,
	ACT_SLAM_THROW_THROW_ND = 241,
	ACT_SLAM_THROW_THROW_ND2 = 242,
	ACT_SLAM_THROW_DRAW = 243,
	ACT_SLAM_THROW_ND_DRAW = 244,
	ACT_SLAM_THROW_TO_STICKWALL = 245,
	ACT_SLAM_THROW_TO_STICKWALL_ND = 246,
	ACT_SLAM_THROW_DETONATE = 247,
	ACT_SLAM_THROW_DETONATOR_HOLSTER = 248,
	ACT_SLAM_THROW_TO_TRIPMINE_ND = 249,
	ACT_SLAM_TRIPMINE_IDLE = 250,
	ACT_SLAM_TRIPMINE_DRAW = 251,
	ACT_SLAM_TRIPMINE_ATTACH = 252,
	ACT_SLAM_TRIPMINE_ATTACH2 = 253,
	ACT_SLAM_TRIPMINE_TO_STICKWALL_ND = 254,
	ACT_SLAM_TRIPMINE_TO_THROW_ND = 255,
	ACT_SLAM_DETONATOR_IDLE = 256,
	ACT_SLAM_DETONATOR_DRAW = 257,
	ACT_SLAM_DETONATOR_DETONATE = 258,
	ACT_SLAM_DETONATOR_HOLSTER = 259,
	ACT_SLAM_DETONATOR_STICKWALL_DRAW = 260,
	ACT_SLAM_DETONATOR_THROW_DRAW = 261,
	ACT_SHOTGUN_RELOAD_START = 262,
	ACT_SHOTGUN_RELOAD_FINISH = 263,
	ACT_SHOTGUN_PUMP = 264,
	ACT_SMG2_IDLE2 = 265,
	ACT_SMG2_FIRE2 = 266,
	ACT_SMG2_DRAW2 = 267,
	ACT_SMG2_RELOAD2 = 268,
	ACT_SMG2_DRYFIRE2 = 269,
	ACT_SMG2_TOAUTO = 270,
	ACT_SMG2_TOBURST = 271,
	ACT_PHYSCANNON_UPGRADE = 272,
	ACT_RANGE_ATTACK_AR1 = 273,
	ACT_RANGE_ATTACK_AR2 = 274,
	ACT_RANGE_ATTACK_AR2_LOW = 275,
	ACT_RANGE_ATTACK_AR2_GRENADE = 276,
	ACT_RANGE_ATTACK_HMG1 = 277,
	ACT_RANGE_ATTACK_ML = 278,
	ACT_RANGE_ATTACK_SMG1 = 279,
	ACT_RANGE_ATTACK_SMG1_LOW = 280,
	ACT_RANGE_ATTACK_SMG2 = 281,
	ACT_RANGE_ATTACK_SHOTGUN = 282,
	ACT_RANGE_ATTACK_SHOTGUN_LOW = 283,
	ACT_RANGE_ATTACK_PISTOL = 284,
	ACT_RANGE_ATTACK_PISTOL_LOW = 285,
	ACT_RANGE_ATTACK_SLAM = 286,
	ACT_RANGE_ATTACK_TRIPWIRE = 287,
	ACT_RANGE_ATTACK_THROW = 288,
	ACT_RANGE_ATTACK_SNIPER_RIFLE = 289,
	ACT_RANGE_ATTACK_RPG = 290,
	ACT_MELEE_ATTACK_SWING = 291,
	ACT_RANGE_AIM_LOW = 292,
	ACT_RANGE_AIM_SMG1_LOW = 293,
	ACT_RANGE_AIM_PISTOL_LOW = 294,
	ACT_RANGE_AIM_AR2_LOW = 295,
	ACT_COVER_PISTOL_LOW = 296,
	ACT_COVER_SMG1_LOW = 297,
	ACT_GESTURE_RANGE_ATTACK_AR1 = 298,
	ACT_GESTURE_RANGE_ATTACK_AR2 = 299,
	ACT_GESTURE_RANGE_ATTACK_AR2_GRENADE = 300,
	ACT_GESTURE_RANGE_ATTACK_HMG1 = 301,
	ACT_GESTURE_RANGE_ATTACK_ML = 302,
	ACT_GESTURE_RANGE_ATTACK_SMG1 = 303,
	ACT_GESTURE_RANGE_ATTACK_SMG1_LOW = 304,
	ACT_GESTURE_RANGE_ATTACK_SMG2 = 305,
	ACT_GESTURE_RANGE_ATTACK_SHOTGUN = 306,
	ACT_GESTURE_RANGE_ATTACK_PISTOL = 307,
	ACT_GESTURE_RANGE_ATTACK_PISTOL_LOW = 308,
	ACT_GESTURE_RANGE_ATTACK_SLAM = 309,
	ACT_GESTURE_RANGE_ATTACK_TRIPWIRE = 310,
	ACT_GESTURE_RANGE_ATTACK_THROW = 311,
	ACT_GESTURE_RANGE_ATTACK_SNIPER_RIFLE = 312,
	ACT_GESTURE_MELEE_ATTACK_SWING = 313,
	ACT_IDLE_RIFLE = 314,
	ACT_IDLE_SMG1 = 315,
	ACT_IDLE_ANGRY_SMG1 = 316,
	ACT_IDLE_PISTOL = 317,
	ACT_IDLE_ANGRY_PISTOL = 318,
	ACT_IDLE_ANGRY_SHOTGUN = 319,
	ACT_IDLE_STEALTH_PISTOL = 320,
	ACT_IDLE_PACKAGE = 321,
	ACT_WALK_PACKAGE = 322,
	ACT_IDLE_SUITCASE = 323,
	ACT_WALK_SUITCASE = 324,
	ACT_IDLE_SMG1_RELAXED = 325,
	ACT_IDLE_SMG1_STIMULATED = 326,
	ACT_WALK_RIFLE_RELAXED = 327,
	ACT_RUN_RIFLE_RELAXED = 328,
	ACT_WALK_RIFLE_STIMULATED = 329,
	ACT_RUN_RIFLE_STIMULATED = 330,
	ACT_IDLE_AIM_RIFLE_STIMULATED = 331,
	ACT_WALK_AIM_RIFLE_STIMULATED = 332,
	ACT_RUN_AIM_RIFLE_STIMULATED = 333,
	ACT_IDLE_SHOTGUN_RELAXED = 334,
	ACT_IDLE_SHOTGUN_STIMULATED = 335,
	ACT_IDLE_SHOTGUN_AGITATED = 336,
	ACT_WALK_ANGRY = 337,
	ACT_POLICE_HARASS1 = 338,
	ACT_POLICE_HARASS2 = 339,
	ACT_IDLE_MANNEDGUN = 340,
	ACT_IDLE_MELEE = 341,
	ACT_IDLE_ANGRY_MELEE = 342,
	ACT_IDLE_RPG_RELAXED = 343,
	ACT_IDLE_RPG = 344,
	ACT_IDLE_ANGRY_RPG = 345,
	ACT_COVER_LOW_RPG = 346,
	ACT_WALK_RPG = 347,
	ACT_RUN_RPG = 348,
	ACT_WALK_CROUCH_RPG = 349,
	ACT_RUN_CROUCH_RPG = 350,
	ACT_WALK_RPG_RELAXED = 351,
	ACT_RUN_RPG_RELAXED = 352,
	ACT_WALK_RIFLE = 353,
	ACT_WALK_AIM_RIFLE = 354,
	ACT_WALK_CROUCH_RIFLE = 355,
	ACT_WALK_CROUCH_AIM_RIFLE = 356,
	ACT_RUN_RIFLE = 357,
	ACT_RUN_AIM_RIFLE = 358,
	ACT_RUN_CROUCH_RIFLE = 359,
	ACT_RUN_CROUCH_AIM_RIFLE = 360,
	ACT_RUN_STEALTH_PISTOL = 361,
	ACT_WALK_AIM_SHOTGUN = 362,
	ACT_RUN_AIM_SHOTGUN = 363,
	ACT_WALK_PISTOL = 364,
	ACT_RUN_PISTOL = 365,
	ACT_WALK_AIM_PISTOL = 366,
	ACT_RUN_AIM_PISTOL = 367,
	ACT_WALK_STEALTH_PISTOL = 368,
	ACT_WALK_AIM_STEALTH_PISTOL = 369,
	ACT_RUN_AIM_STEALTH_PISTOL = 370,
	ACT_RELOAD_PISTOL = 371,
	ACT_RELOAD_PISTOL_LOW = 372,
	ACT_RELOAD_SMG1 = 373,
	ACT_RELOAD_SMG1_LOW = 374,
	ACT_RELOAD_SHOTGUN = 375,
	ACT_RELOAD_SHOTGUN_LOW = 376,
	ACT_GESTURE_RELOAD = 377,
	ACT_GESTURE_RELOAD_PISTOL = 378,
	ACT_GESTURE_RELOAD_SMG1 = 379,
	ACT_GESTURE_RELOAD_SHOTGUN = 380,
	ACT_BUSY_LEAN_LEFT = 381,
	ACT_BUSY_LEAN_LEFT_ENTRY = 382,
	ACT_BUSY_LEAN_LEFT_EXIT = 383,
	ACT_BUSY_LEAN_BACK = 384,
	ACT_BUSY_LEAN_BACK_ENTRY = 385,
	ACT_BUSY_LEAN_BACK_EXIT = 386,
	ACT_BUSY_SIT_GROUND = 387,
	ACT_BUSY_SIT_GROUND_ENTRY = 388,
	ACT_BUSY_SIT_GROUND_EXIT = 389,
	ACT_BUSY_SIT_CHAIR = 390,
	ACT_BUSY_SIT_CHAIR_ENTRY = 391,
	ACT_BUSY_SIT_CHAIR_EXIT = 392,
	ACT_BUSY_STAND = 393,
	ACT_BUSY_QUEUE = 394,
	ACT_DUCK_DODGE = 395,
	ACT_DIE_BARNACLE_SWALLOW = 396,
	ACT_GESTURE_BARNACLE_STRANGLE = 397,
	ACT_PHYSCANNON_DETACH = 398,
	ACT_PHYSCANNON_ANIMATE = 399,
	ACT_PHYSCANNON_ANIMATE_PRE = 400,
	ACT_PHYSCANNON_ANIMATE_POST = 401,
	ACT_DIE_FRONTSIDE = 402,
	ACT_DIE_RIGHTSIDE = 403,
	ACT_DIE_BACKSIDE = 404,
	ACT_DIE_LEFTSIDE = 405,
	ACT_DIE_CROUCH_FRONTSIDE = 406,
	ACT_DIE_CROUCH_RIGHTSIDE = 407,
	ACT_DIE_CROUCH_BACKSIDE = 408,
	ACT_DIE_CROUCH_LEFTSIDE = 409,
	ACT_DIE_INCAP = 410,
	ACT_DIE_STANDING = 411,
	ACT_OPEN_DOOR = 412,
	ACT_DI_ALYX_ZOMBIE_MELEE = 413,
	ACT_DI_ALYX_ZOMBIE_TORSO_MELEE = 414,
	ACT_DI_ALYX_HEADCRAB_MELEE = 415,
	ACT_DI_ALYX_ANTLION = 416,
	ACT_DI_ALYX_ZOMBIE_SHOTGUN64 = 417,
	ACT_DI_ALYX_ZOMBIE_SHOTGUN26 = 418,
	ACT_READINESS_RELAXED_TO_STIMULATED = 419,
	ACT_READINESS_RELAXED_TO_STIMULATED_WALK = 420,
	ACT_READINESS_AGITATED_TO_STIMULATED = 421,
	ACT_READINESS_STIMULATED_TO_RELAXED = 422,
	ACT_READINESS_PISTOL_RELAXED_TO_STIMULATED = 423,
	ACT_READINESS_PISTOL_RELAXED_TO_STIMULATED_WALK = 424,
	ACT_READINESS_PISTOL_AGITATED_TO_STIMULATED = 425,
	ACT_READINESS_PISTOL_STIMULATED_TO_RELAXED = 426,
	ACT_IDLE_CARRY = 427,
	ACT_WALK_CARRY = 428,
	ACT_STARTDYING = 429,
	ACT_DYINGLOOP = 430,
	ACT_DYINGTODEAD = 431,
	ACT_RIDE_MANNED_GUN = 432,
	ACT_VM_SPRINT_ENTER = 433,
	ACT_VM_SPRINT_IDLE = 434,
	ACT_VM_SPRINT_LEAVE = 435,
	ACT_FIRE_START = 436,
	ACT_FIRE_LOOP = 437,
	ACT_FIRE_END = 438,
	ACT_CROUCHING_GRENADEIDLE = 439,
	ACT_CROUCHING_GRENADEREADY = 440,
	ACT_CROUCHING_PRIMARYATTACK = 441,
	ACT_OVERLAY_GRENADEIDLE = 442,
	ACT_OVERLAY_GRENADEREADY = 443,
	ACT_OVERLAY_PRIMARYATTACK = 444,
	ACT_OVERLAY_SHIELD_UP = 445,
	ACT_OVERLAY_SHIELD_DOWN = 446,
	ACT_OVERLAY_SHIELD_UP_IDLE = 447,
	ACT_OVERLAY_SHIELD_ATTACK = 448,
	ACT_OVERLAY_SHIELD_KNOCKBACK = 449,
	ACT_SHIELD_UP = 450,
	ACT_SHIELD_DOWN = 451,
	ACT_SHIELD_UP_IDLE = 452,
	ACT_SHIELD_ATTACK = 453,
	ACT_SHIELD_KNOCKBACK = 454,
	ACT_CROUCHING_SHIELD_UP = 455,
	ACT_CROUCHING_SHIELD_DOWN = 456,
	ACT_CROUCHING_SHIELD_UP_IDLE = 457,
	ACT_CROUCHING_SHIELD_ATTACK = 458,
	ACT_CROUCHING_SHIELD_KNOCKBACK = 459,
	ACT_TURNRIGHT45 = 460,
	ACT_TURNLEFT45 = 461,
	ACT_TURN = 462,
	ACT_OBJ_ASSEMBLING = 463,
	ACT_OBJ_DISMANTLING = 464,
	ACT_OBJ_STARTUP = 465,
	ACT_OBJ_RUNNING = 466,
	ACT_OBJ_IDLE = 467,
	ACT_OBJ_PLACING = 468,
	ACT_OBJ_DETERIORATING = 469,
	ACT_OBJ_UPGRADING = 470,
	ACT_DEPLOY = 471,
	ACT_DEPLOY_IDLE = 472,
	ACT_UNDEPLOY = 473,
	ACT_CROSSBOW_DRAW_UNLOADED = 474,
	ACT_GAUSS_SPINUP = 475,
	ACT_GAUSS_SPINCYCLE = 476,
	ACT_VM_PRIMARYATTACK_SILENCED = 477,
	ACT_VM_RELOAD_SILENCED = 478,
	ACT_VM_DRYFIRE_SILENCED = 479,
	ACT_VM_IDLE_SILENCED = 480,
	ACT_VM_DRAW_SILENCED = 481,
	ACT_VM_IDLE_EMPTY_LEFT = 482,
	ACT_VM_DRYFIRE_LEFT = 483,
	ACT_VM_IS_DRAW = 484,
	ACT_VM_IS_HOLSTER = 485,
	ACT_VM_IS_IDLE = 486,
	ACT_VM_IS_PRIMARYATTACK = 487,
	ACT_PLAYER_IDLE_FIRE = 488,
	ACT_PLAYER_CROUCH_FIRE = 489,
	ACT_PLAYER_CROUCH_WALK_FIRE = 490,
	ACT_PLAYER_WALK_FIRE = 491,
	ACT_PLAYER_RUN_FIRE = 492,
	ACT_IDLETORUN = 493,
	ACT_RUNTOIDLE = 494,
	ACT_VM_DRAW_DEPLOYED = 495,
	ACT_HL2MP_IDLE_MELEE = 496,
	ACT_HL2MP_RUN_MELEE = 497,
	ACT_HL2MP_IDLE_CROUCH_MELEE = 498,
	ACT_HL2MP_WALK_CROUCH_MELEE = 499,
	ACT_HL2MP_GESTURE_RANGE_ATTACK_MELEE = 500,
	ACT_HL2MP_GESTURE_RELOAD_MELEE = 501,
	ACT_HL2MP_JUMP_MELEE = 502,
	ACT_MP_STAND_IDLE = 503,
	ACT_MP_CROUCH_IDLE = 504,
	ACT_MP_CROUCH_DEPLOYED_IDLE = 505,
	ACT_MP_CROUCH_DEPLOYED = 506,
	ACT_MP_DEPLOYED_IDLE = 507,
	ACT_MP_RUN = 508,
	ACT_MP_WALK = 509,
	ACT_MP_AIRWALK = 510,
	ACT_MP_CROUCHWALK = 511,
	ACT_MP_SPRINT = 512,
	ACT_MP_JUMP = 513,
	ACT_MP_JUMP_START = 514,
	ACT_MP_JUMP_FLOAT = 515,
	ACT_MP_JUMP_LAND = 516,
	ACT_MP_DOUBLEJUMP = 517,
	ACT_MP_SWIM = 518,
	ACT_MP_DEPLOYED = 519,
	ACT_MP_SWIM_DEPLOYED = 520,
	ACT_MP_VCD = 521,
	ACT_MP_ATTACK_STAND_PRIMARYFIRE = 522,
	ACT_MP_ATTACK_STAND_PRIMARYFIRE_DEPLOYED = 523,
	ACT_MP_ATTACK_STAND_SECONDARYFIRE = 524,
	ACT_MP_ATTACK_STAND_GRENADE = 525,
	ACT_MP_ATTACK_CROUCH_PRIMARYFIRE = 526,
	ACT_MP_ATTACK_CROUCH_PRIMARYFIRE_DEPLOYED = 527,
	ACT_MP_ATTACK_CROUCH_SECONDARYFIRE = 528,
	ACT_MP_ATTACK_CROUCH_GRENADE = 529,
	ACT_MP_ATTACK_SWIM_PRIMARYFIRE = 530,
	ACT_MP_ATTACK_SWIM_SECONDARYFIRE = 531,
	ACT_MP_ATTACK_SWIM_GRENADE = 532,
	ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE = 533,
	ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE = 534,
	ACT_MP_ATTACK_AIRWALK_GRENADE = 535,
	ACT_MP_RELOAD_STAND = 536,
	ACT_MP_RELOAD_STAND_LOOP = 537,
	ACT_MP_RELOAD_STAND_END = 538,
	ACT_MP_RELOAD_CROUCH = 539,
	ACT_MP_RELOAD_CROUCH_LOOP = 540,
	ACT_MP_RELOAD_CROUCH_END = 541,
	ACT_MP_RELOAD_SWIM = 542,
	ACT_MP_RELOAD_SWIM_LOOP = 543,
	ACT_MP_RELOAD_SWIM_END = 544,
	ACT_MP_RELOAD_AIRWALK = 545,
	ACT_MP_RELOAD_AIRWALK_LOOP = 546,
	ACT_MP_RELOAD_AIRWALK_END = 547,
	ACT_MP_ATTACK_STAND_PREFIRE = 548,
	ACT_MP_ATTACK_STAND_POSTFIRE = 549,
	ACT_MP_ATTACK_STAND_STARTFIRE = 550,
	ACT_MP_ATTACK_CROUCH_PREFIRE = 551,
	ACT_MP_ATTACK_CROUCH_POSTFIRE = 552,
	ACT_MP_ATTACK_SWIM_PREFIRE = 553,
	ACT_MP_ATTACK_SWIM_POSTFIRE = 554,
	ACT_MP_STAND_PRIMARY = 555,
	ACT_MP_CROUCH_PRIMARY = 556,
	ACT_MP_RUN_PRIMARY = 557,
	ACT_MP_WALK_PRIMARY = 558,
	ACT_MP_AIRWALK_PRIMARY = 559,
	ACT_MP_CROUCHWALK_PRIMARY = 560,
	ACT_MP_JUMP_PRIMARY = 561,
	ACT_MP_JUMP_START_PRIMARY = 562,
	ACT_MP_JUMP_FLOAT_PRIMARY = 563,
	ACT_MP_JUMP_LAND_PRIMARY = 564,
	ACT_MP_SWIM_PRIMARY = 565,
	ACT_MP_DEPLOYED_PRIMARY = 566,
	ACT_MP_SWIM_DEPLOYED_PRIMARY = 567,
	ACT_MP_ATTACK_STAND_PRIMARY = 568,
	ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED = 569,
	ACT_MP_ATTACK_CROUCH_PRIMARY = 570,
	ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED = 571,
	ACT_MP_ATTACK_SWIM_PRIMARY = 572,
	ACT_MP_ATTACK_AIRWALK_PRIMARY = 573,
	ACT_MP_RELOAD_STAND_PRIMARY = 574,
	ACT_MP_RELOAD_STAND_PRIMARY_LOOP = 575,
	ACT_MP_RELOAD_STAND_PRIMARY_END = 576,
	ACT_MP_RELOAD_CROUCH_PRIMARY = 577,
	ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP = 578,
	ACT_MP_RELOAD_CROUCH_PRIMARY_END = 579,
	ACT_MP_RELOAD_SWIM_PRIMARY = 580,
	ACT_MP_RELOAD_SWIM_PRIMARY_LOOP = 581,
	ACT_MP_RELOAD_SWIM_PRIMARY_END = 582,
	ACT_MP_RELOAD_AIRWALK_PRIMARY = 583,
	ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP = 584,
	ACT_MP_RELOAD_AIRWALK_PRIMARY_END = 585,
	ACT_MP_ATTACK_STAND_GRENADE_PRIMARY = 586,
	ACT_MP_ATTACK_CROUCH_GRENADE_PRIMARY = 587,
	ACT_MP_ATTACK_SWIM_GRENADE_PRIMARY = 588,
	ACT_MP_ATTACK_AIRWALK_GRENADE_PRIMARY = 589,
	ACT_MP_STAND_SECONDARY = 590,
	ACT_MP_CROUCH_SECONDARY = 591,
	ACT_MP_RUN_SECONDARY = 592,
	ACT_MP_WALK_SECONDARY = 593,
	ACT_MP_AIRWALK_SECONDARY = 594,
	ACT_MP_CROUCHWALK_SECONDARY = 595,
	ACT_MP_JUMP_SECONDARY = 596,
	ACT_MP_JUMP_START_SECONDARY = 597,
	ACT_MP_JUMP_FLOAT_SECONDARY = 598,
	ACT_MP_JUMP_LAND_SECONDARY = 599,
	ACT_MP_SWIM_SECONDARY = 600,
	ACT_MP_ATTACK_STAND_SECONDARY = 601,
	ACT_MP_ATTACK_CROUCH_SECONDARY = 602,
	ACT_MP_ATTACK_SWIM_SECONDARY = 603,
	ACT_MP_ATTACK_AIRWALK_SECONDARY = 604,
	ACT_MP_RELOAD_STAND_SECONDARY = 605,
	ACT_MP_RELOAD_STAND_SECONDARY_LOOP = 606,
	ACT_MP_RELOAD_STAND_SECONDARY_END = 607,
	ACT_MP_RELOAD_CROUCH_SECONDARY = 608,
	ACT_MP_RELOAD_CROUCH_SECONDARY_LOOP = 609,
	ACT_MP_RELOAD_CROUCH_SECONDARY_END = 610,
	ACT_MP_RELOAD_SWIM_SECONDARY = 611,
	ACT_MP_RELOAD_SWIM_SECONDARY_LOOP = 612,
	ACT_MP_RELOAD_SWIM_SECONDARY_END = 613,
	ACT_MP_RELOAD_AIRWALK_SECONDARY = 614,
	ACT_MP_RELOAD_AIRWALK_SECONDARY_LOOP = 615,
	ACT_MP_RELOAD_AIRWALK_SECONDARY_END = 616,
	ACT_MP_ATTACK_STAND_GRENADE_SECONDARY = 617,
	ACT_MP_ATTACK_CROUCH_GRENADE_SECONDARY = 618,
	ACT_MP_ATTACK_SWIM_GRENADE_SECONDARY = 619,
	ACT_MP_ATTACK_AIRWALK_GRENADE_SECONDARY = 620,
	ACT_MP_STAND_MELEE = 621,
	ACT_MP_CROUCH_MELEE = 622,
	ACT_MP_RUN_MELEE = 623,
	ACT_MP_WALK_MELEE = 624,
	ACT_MP_AIRWALK_MELEE = 625,
	ACT_MP_CROUCHWALK_MELEE = 626,
	ACT_MP_JUMP_MELEE = 627,
	ACT_MP_JUMP_START_MELEE = 628,
	ACT_MP_JUMP_FLOAT_MELEE = 629,
	ACT_MP_JUMP_LAND_MELEE = 630,
	ACT_MP_SWIM_MELEE = 631,
	ACT_MP_ATTACK_STAND_MELEE = 632,
	ACT_MP_ATTACK_STAND_MELEE_SECONDARY = 633,
	ACT_MP_ATTACK_CROUCH_MELEE = 634,
	ACT_MP_ATTACK_CROUCH_MELEE_SECONDARY = 635,
	ACT_MP_ATTACK_SWIM_MELEE = 636,
	ACT_MP_ATTACK_AIRWALK_MELEE = 637,
	ACT_MP_ATTACK_STAND_GRENADE_MELEE = 638,
	ACT_MP_ATTACK_CROUCH_GRENADE_MELEE = 639,
	ACT_MP_ATTACK_SWIM_GRENADE_MELEE = 640,
	ACT_MP_ATTACK_AIRWALK_GRENADE_MELEE = 641,
	ACT_MP_STAND_ITEM1 = 642,
	ACT_MP_CROUCH_ITEM1 = 643,
	ACT_MP_RUN_ITEM1 = 644,
	ACT_MP_WALK_ITEM1 = 645,
	ACT_MP_AIRWALK_ITEM1 = 646,
	ACT_MP_CROUCHWALK_ITEM1 = 647,
	ACT_MP_JUMP_ITEM1 = 648,
	ACT_MP_JUMP_START_ITEM1 = 649,
	ACT_MP_JUMP_FLOAT_ITEM1 = 650,
	ACT_MP_JUMP_LAND_ITEM1 = 651,
	ACT_MP_SWIM_ITEM1 = 652,
	ACT_MP_ATTACK_STAND_ITEM1 = 653,
	ACT_MP_ATTACK_STAND_ITEM1_SECONDARY = 654,
	ACT_MP_ATTACK_CROUCH_ITEM1 = 655,
	ACT_MP_ATTACK_CROUCH_ITEM1_SECONDARY = 656,
	ACT_MP_ATTACK_SWIM_ITEM1 = 657,
	ACT_MP_ATTACK_AIRWALK_ITEM1 = 658,
	ACT_MP_STAND_ITEM2 = 659,
	ACT_MP_CROUCH_ITEM2 = 660,
	ACT_MP_RUN_ITEM2 = 661,
	ACT_MP_WALK_ITEM2 = 662,
	ACT_MP_AIRWALK_ITEM2 = 663,
	ACT_MP_CROUCHWALK_ITEM2 = 664,
	ACT_MP_JUMP_ITEM2 = 665,
	ACT_MP_JUMP_START_ITEM2 = 666,
	ACT_MP_JUMP_FLOAT_ITEM2 = 667,
	ACT_MP_JUMP_LAND_ITEM2 = 668,
	ACT_MP_SWIM_ITEM2 = 669,
	ACT_MP_ATTACK_STAND_ITEM2 = 670,
	ACT_MP_ATTACK_STAND_ITEM2_SECONDARY = 671,
	ACT_MP_ATTACK_CROUCH_ITEM2 = 672,
	ACT_MP_ATTACK_CROUCH_ITEM2_SECONDARY = 673,
	ACT_MP_ATTACK_SWIM_ITEM2 = 674,
	ACT_MP_ATTACK_AIRWALK_ITEM2 = 675,
	ACT_MP_GESTURE_FLINCH = 676,
	ACT_MP_GESTURE_FLINCH_PRIMARY = 677,
	ACT_MP_GESTURE_FLINCH_SECONDARY = 678,
	ACT_MP_GESTURE_FLINCH_MELEE = 679,
	ACT_MP_GESTURE_FLINCH_ITEM1 = 680,
	ACT_MP_GESTURE_FLINCH_ITEM2 = 681,
	ACT_MP_GESTURE_FLINCH_HEAD = 682,
	ACT_MP_GESTURE_FLINCH_CHEST = 683,
	ACT_MP_GESTURE_FLINCH_STOMACH = 684,
	ACT_MP_GESTURE_FLINCH_LEFTARM = 685,
	ACT_MP_GESTURE_FLINCH_RIGHTARM = 686,
	ACT_MP_GESTURE_FLINCH_LEFTLEG = 687,
	ACT_MP_GESTURE_FLINCH_RIGHTLEG = 688,
	ACT_MP_GRENADE1_DRAW = 689,
	ACT_MP_GRENADE1_IDLE = 690,
	ACT_MP_GRENADE1_ATTACK = 691,
	ACT_MP_GRENADE2_DRAW = 692,
	ACT_MP_GRENADE2_IDLE = 693,
	ACT_MP_GRENADE2_ATTACK = 694,
	ACT_MP_PRIMARY_GRENADE1_DRAW = 695,
	ACT_MP_PRIMARY_GRENADE1_IDLE = 696,
	ACT_MP_PRIMARY_GRENADE1_ATTACK = 697,
	ACT_MP_PRIMARY_GRENADE2_DRAW = 698,
	ACT_MP_PRIMARY_GRENADE2_IDLE = 699,
	ACT_MP_PRIMARY_GRENADE2_ATTACK = 700,
	ACT_MP_SECONDARY_GRENADE1_DRAW = 701,
	ACT_MP_SECONDARY_GRENADE1_IDLE = 702,
	ACT_MP_SECONDARY_GRENADE1_ATTACK = 703,
	ACT_MP_SECONDARY_GRENADE2_DRAW = 704,
	ACT_MP_SECONDARY_GRENADE2_IDLE = 705,
	ACT_MP_SECONDARY_GRENADE2_ATTACK = 706,
	ACT_MP_MELEE_GRENADE1_DRAW = 707,
	ACT_MP_MELEE_GRENADE1_IDLE = 708,
	ACT_MP_MELEE_GRENADE1_ATTACK = 709,
	ACT_MP_MELEE_GRENADE2_DRAW = 710,
	ACT_MP_MELEE_GRENADE2_IDLE = 711,
	ACT_MP_MELEE_GRENADE2_ATTACK = 712,
	ACT_MP_ITEM1_GRENADE1_DRAW = 713,
	ACT_MP_ITEM1_GRENADE1_IDLE = 714,
	ACT_MP_ITEM1_GRENADE1_ATTACK = 715,
	ACT_MP_ITEM1_GRENADE2_DRAW = 716,
	ACT_MP_ITEM1_GRENADE2_IDLE = 717,
	ACT_MP_ITEM1_GRENADE2_ATTACK = 718,
	ACT_MP_ITEM2_GRENADE1_DRAW = 719,
	ACT_MP_ITEM2_GRENADE1_IDLE = 720,
	ACT_MP_ITEM2_GRENADE1_ATTACK = 721,
	ACT_MP_ITEM2_GRENADE2_DRAW = 722,
	ACT_MP_ITEM2_GRENADE2_IDLE = 723,
	ACT_MP_ITEM2_GRENADE2_ATTACK = 724,
	ACT_MP_STAND_BUILDING = 725,
	ACT_MP_CROUCH_BUILDING = 726,
	ACT_MP_RUN_BUILDING = 727,
	ACT_MP_WALK_BUILDING = 728,
	ACT_MP_AIRWALK_BUILDING = 729,
	ACT_MP_CROUCHWALK_BUILDING = 730,
	ACT_MP_JUMP_BUILDING = 731,
	ACT_MP_JUMP_START_BUILDING = 732,
	ACT_MP_JUMP_FLOAT_BUILDING = 733,
	ACT_MP_JUMP_LAND_BUILDING = 734,
	ACT_MP_SWIM_BUILDING = 735,
	ACT_MP_ATTACK_STAND_BUILDING = 736,
	ACT_MP_ATTACK_CROUCH_BUILDING = 737,
	ACT_MP_ATTACK_SWIM_BUILDING = 738,
	ACT_MP_ATTACK_AIRWALK_BUILDING = 739,
	ACT_MP_ATTACK_STAND_GRENADE_BUILDING = 740,
	ACT_MP_ATTACK_CROUCH_GRENADE_BUILDING = 741,
	ACT_MP_ATTACK_SWIM_GRENADE_BUILDING = 742,
	ACT_MP_ATTACK_AIRWALK_GRENADE_BUILDING = 743,
	ACT_MP_STAND_PDA = 744,
	ACT_MP_CROUCH_PDA = 745,
	ACT_MP_RUN_PDA = 746,
	ACT_MP_WALK_PDA = 747,
	ACT_MP_AIRWALK_PDA = 748,
	ACT_MP_CROUCHWALK_PDA = 749,
	ACT_MP_JUMP_PDA = 750,
	ACT_MP_JUMP_START_PDA = 751,
	ACT_MP_JUMP_FLOAT_PDA = 752,
	ACT_MP_JUMP_LAND_PDA = 753,
	ACT_MP_SWIM_PDA = 754,
	ACT_MP_ATTACK_STAND_PDA = 755,
	ACT_MP_ATTACK_SWIM_PDA = 756,
	ACT_MP_GESTURE_VC_HANDMOUTH = 757,
	ACT_MP_GESTURE_VC_FINGERPOINT = 758,
	ACT_MP_GESTURE_VC_FISTPUMP = 759,
	ACT_MP_GESTURE_VC_THUMBSUP = 760,
	ACT_MP_GESTURE_VC_NODYES = 761,
	ACT_MP_GESTURE_VC_NODNO = 762,
	ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY = 763,
	ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY = 764,
	ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY = 765,
	ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY = 766,
	ACT_MP_GESTURE_VC_NODYES_PRIMARY = 767,
	ACT_MP_GESTURE_VC_NODNO_PRIMARY = 768,
	ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY = 769,
	ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY = 770,
	ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY = 771,
	ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY = 772,
	ACT_MP_GESTURE_VC_NODYES_SECONDARY = 773,
	ACT_MP_GESTURE_VC_NODNO_SECONDARY = 774,
	ACT_MP_GESTURE_VC_HANDMOUTH_MELEE = 775,
	ACT_MP_GESTURE_VC_FINGERPOINT_MELEE = 776,
	ACT_MP_GESTURE_VC_FISTPUMP_MELEE = 777,
	ACT_MP_GESTURE_VC_THUMBSUP_MELEE = 778,
	ACT_MP_GESTURE_VC_NODYES_MELEE = 779,
	ACT_MP_GESTURE_VC_NODNO_MELEE = 780,
	ACT_MP_GESTURE_VC_HANDMOUTH_ITEM1 = 781,
	ACT_MP_GESTURE_VC_FINGERPOINT_ITEM1 = 782,
	ACT_MP_GESTURE_VC_FISTPUMP_ITEM1 = 783,
	ACT_MP_GESTURE_VC_THUMBSUP_ITEM1 = 784,
	ACT_MP_GESTURE_VC_NODYES_ITEM1 = 785,
	ACT_MP_GESTURE_VC_NODNO_ITEM1 = 786,
	ACT_MP_GESTURE_VC_HANDMOUTH_ITEM2 = 787,
	ACT_MP_GESTURE_VC_FINGERPOINT_ITEM2 = 788,
	ACT_MP_GESTURE_VC_FISTPUMP_ITEM2 = 789,
	ACT_MP_GESTURE_VC_THUMBSUP_ITEM2 = 790,
	ACT_MP_GESTURE_VC_NODYES_ITEM2 = 791,
	ACT_MP_GESTURE_VC_NODNO_ITEM2 = 792,
	ACT_MP_GESTURE_VC_HANDMOUTH_BUILDING = 793,
	ACT_MP_GESTURE_VC_FINGERPOINT_BUILDING = 794,
	ACT_MP_GESTURE_VC_FISTPUMP_BUILDING = 795,
	ACT_MP_GESTURE_VC_THUMBSUP_BUILDING = 796,
	ACT_MP_GESTURE_VC_NODYES_BUILDING = 797,
	ACT_MP_GESTURE_VC_NODNO_BUILDING = 798,
	ACT_MP_GESTURE_VC_HANDMOUTH_PDA = 799,
	ACT_MP_GESTURE_VC_FINGERPOINT_PDA = 800,
	ACT_MP_GESTURE_VC_FISTPUMP_PDA = 801,
	ACT_MP_GESTURE_VC_THUMBSUP_PDA = 802,
	ACT_MP_GESTURE_VC_NODYES_PDA = 803,
	ACT_MP_GESTURE_VC_NODNO_PDA = 804,
	ACT_VM_UNUSABLE = 805,
	ACT_VM_UNUSABLE_TO_USABLE = 806,
	ACT_VM_USABLE_TO_UNUSABLE = 807,
	ACT_PRIMARY_VM_DRAW = 808,
	ACT_PRIMARY_VM_HOLSTER = 809,
	ACT_PRIMARY_VM_IDLE = 810,
	ACT_PRIMARY_VM_PULLBACK = 811,
	ACT_PRIMARY_VM_PRIMARYATTACK = 812,
	ACT_PRIMARY_VM_SECONDARYATTACK = 813,
	ACT_PRIMARY_VM_RELOAD = 814,
	ACT_PRIMARY_VM_DRYFIRE = 815,
	ACT_PRIMARY_VM_IDLE_TO_LOWERED = 816,
	ACT_PRIMARY_VM_IDLE_LOWERED = 817,
	ACT_PRIMARY_VM_LOWERED_TO_IDLE = 818,
	ACT_SECONDARY_VM_DRAW = 819,
	ACT_SECONDARY_VM_HOLSTER = 820,
	ACT_SECONDARY_VM_IDLE = 821,
	ACT_SECONDARY_VM_PULLBACK = 822,
	ACT_SECONDARY_VM_PRIMARYATTACK = 823,
	ACT_SECONDARY_VM_SECONDARYATTACK = 824,
	ACT_SECONDARY_VM_RELOAD = 825,
	ACT_SECONDARY_VM_DRYFIRE = 826,
	ACT_SECONDARY_VM_IDLE_TO_LOWERED = 827,
	ACT_SECONDARY_VM_IDLE_LOWERED = 828,
	ACT_SECONDARY_VM_LOWERED_TO_IDLE = 829,
	ACT_MELEE_VM_DRAW = 830,
	ACT_MELEE_VM_HOLSTER = 831,
	ACT_MELEE_VM_IDLE = 832,
	ACT_MELEE_VM_PULLBACK = 833,
	ACT_MELEE_VM_PRIMARYATTACK = 834,
	ACT_MELEE_VM_SECONDARYATTACK = 835,
	ACT_MELEE_VM_RELOAD = 836,
	ACT_MELEE_VM_DRYFIRE = 837,
	ACT_MELEE_VM_IDLE_TO_LOWERED = 838,
	ACT_MELEE_VM_IDLE_LOWERED = 839,
	ACT_MELEE_VM_LOWERED_TO_IDLE = 840,
	ACT_PDA_VM_DRAW = 841,
	ACT_PDA_VM_HOLSTER = 842,
	ACT_PDA_VM_IDLE = 843,
	ACT_PDA_VM_PULLBACK = 844,
	ACT_PDA_VM_PRIMARYATTACK = 845,
	ACT_PDA_VM_SECONDARYATTACK = 846,
	ACT_PDA_VM_RELOAD = 847,
	ACT_PDA_VM_DRYFIRE = 848,
	ACT_PDA_VM_IDLE_TO_LOWERED = 849,
	ACT_PDA_VM_IDLE_LOWERED = 850,
	ACT_PDA_VM_LOWERED_TO_IDLE = 851,
	ACT_ITEM1_VM_DRAW = 852,
	ACT_ITEM1_VM_HOLSTER = 853,
	ACT_ITEM1_VM_IDLE = 854,
	ACT_ITEM1_VM_PULLBACK = 855,
	ACT_ITEM1_VM_PRIMARYATTACK = 856,
	ACT_ITEM1_VM_SECONDARYATTACK = 857,
	ACT_ITEM1_VM_RELOAD = 858,
	ACT_ITEM1_VM_DRYFIRE = 859,
	ACT_ITEM1_VM_IDLE_TO_LOWERED = 860,
	ACT_ITEM1_VM_IDLE_LOWERED = 861,
	ACT_ITEM1_VM_LOWERED_TO_IDLE = 862,
	ACT_ITEM2_VM_DRAW = 863,
	ACT_ITEM2_VM_HOLSTER = 864,
	ACT_ITEM2_VM_IDLE = 865,
	ACT_ITEM2_VM_PULLBACK = 866,
	ACT_ITEM2_VM_PRIMARYATTACK = 867,
	ACT_ITEM2_VM_SECONDARYATTACK = 868,
	ACT_ITEM2_VM_RELOAD = 869,
	ACT_ITEM2_VM_DRYFIRE = 870,
	ACT_ITEM2_VM_IDLE_TO_LOWERED = 871,
	ACT_ITEM2_VM_IDLE_LOWERED = 872,
	ACT_ITEM2_VM_LOWERED_TO_IDLE = 873,
	ACT_RELOAD_SUCCEED = 874,
	ACT_RELOAD_FAIL = 875,
	ACT_WALK_AIM_AUTOGUN = 876,
	ACT_RUN_AIM_AUTOGUN = 877,
	ACT_IDLE_AUTOGUN = 878,
	ACT_IDLE_AIM_AUTOGUN = 879,
	ACT_RELOAD_AUTOGUN = 880,
	ACT_CROUCH_IDLE_AUTOGUN = 881,
	ACT_RANGE_ATTACK_AUTOGUN = 882,
	ACT_JUMP_AUTOGUN = 883,
	ACT_IDLE_AIM_PISTOL = 884,
	ACT_WALK_AIM_DUAL = 885,
	ACT_RUN_AIM_DUAL = 886,
	ACT_IDLE_DUAL = 887,
	ACT_IDLE_AIM_DUAL = 888,
	ACT_RELOAD_DUAL = 889,
	ACT_CROUCH_IDLE_DUAL = 890,
	ACT_RANGE_ATTACK_DUAL = 891,
	ACT_JUMP_DUAL = 892,
	ACT_IDLE_AIM_SHOTGUN = 893,
	ACT_CROUCH_IDLE_SHOTGUN = 894,
	ACT_IDLE_AIM_RIFLE = 895,
	ACT_CROUCH_IDLE_RIFLE = 896,
	ACT_RANGE_ATTACK_RIFLE = 897,
	ACT_SLEEP = 898,
	ACT_WAKE = 899,
	ACT_FLICK_LEFT = 900,
	ACT_FLICK_LEFT_MIDDLE = 901,
	ACT_FLICK_RIGHT_MIDDLE = 902,
	ACT_FLICK_RIGHT = 903,
	ACT_SPINAROUND = 904,
	ACT_PREP_TO_FIRE = 905,
	ACT_FIRE = 906,
	ACT_FIRE_RECOVER = 907,
	ACT_SPRAY = 908,
	ACT_PREP_EXPLODE = 909,
	ACT_EXPLODE = 910,
	ACT_SCRIPT_CUSTOM_0 = 911,
	ACT_SCRIPT_CUSTOM_1 = 912,
	ACT_SCRIPT_CUSTOM_2 = 913,
	ACT_SCRIPT_CUSTOM_3 = 914,
	ACT_SCRIPT_CUSTOM_4 = 915,
	ACT_SCRIPT_CUSTOM_5 = 916,
	ACT_SCRIPT_CUSTOM_6 = 917,
	ACT_SCRIPT_CUSTOM_7 = 918,
	ACT_SCRIPT_CUSTOM_8 = 919,
	ACT_SCRIPT_CUSTOM_9 = 920,
	ACT_SCRIPT_CUSTOM_10 = 921,
	ACT_SCRIPT_CUSTOM_11 = 922,
	ACT_SCRIPT_CUSTOM_12 = 923,
	ACT_SCRIPT_CUSTOM_13 = 924,
	ACT_SCRIPT_CUSTOM_14 = 925,
	ACT_SCRIPT_CUSTOM_15 = 926,
	ACT_SCRIPT_CUSTOM_16 = 927,
	ACT_SCRIPT_CUSTOM_17 = 928,
	ACT_SCRIPT_CUSTOM_18 = 929,
	ACT_SCRIPT_CUSTOM_19 = 930,
	ACT_SCRIPT_CUSTOM_20 = 931,
	ACT_SCRIPT_CUSTOM_21 = 932,
	ACT_SCRIPT_CUSTOM_22 = 933,
	ACT_SCRIPT_CUSTOM_23 = 934,
	ACT_SCRIPT_CUSTOM_24 = 935,
	ACT_SCRIPT_CUSTOM_25 = 936,
	ACT_SCRIPT_CUSTOM_26 = 937,
	ACT_SCRIPT_CUSTOM_27 = 938,
	ACT_SCRIPT_CUSTOM_28 = 939,
	ACT_SCRIPT_CUSTOM_29 = 940,
	ACT_SCRIPT_CUSTOM_30 = 941,
	ACT_SCRIPT_CUSTOM_31 = 942,
};

enum class BeamClipStyle_t : unsigned long
{
	kNOCLIP = 0,
	kGEOCLIP = 1,
	kMODELCLIP = 2,
	kBEAMCLIPSTYLE_NUMBITS = 2,
};

enum class BeamType_t : unsigned long
{
	BEAM_INVALID = 0,
	BEAM_POINTS = 1,
	BEAM_ENTPOINT = 2,
	BEAM_ENTS = 3,
	BEAM_HOSE = 4,
	BEAM_SPLINE = 5,
	BEAM_LASER = 6,
};

enum class BlurFilterType_t : unsigned long
{
	BLURFILTER_GAUSSIAN = 0,
	BLURFILTER_BOX = 1,
};

enum class BundleType_t : unsigned long
{
	BUNDLE_TYPE_NONE = 0,
	BUNDLE_TYPE_POSITION_SPEED = 1,
	BUNDLE_TYPE_NORMAL_WRINKLE = 2,
	BUNDLE_TYPE_COUNT = 3,
};

enum class CLICK_BEHAVIORS : unsigned long
{
	DOTA_CLICK_BEHAVIOR_NONE = 0,
	DOTA_CLICK_BEHAVIOR_MOVE = 1,
	DOTA_CLICK_BEHAVIOR_ATTACK = 2,
	DOTA_CLICK_BEHAVIOR_CAST = 3,
	DOTA_CLICK_BEHAVIOR_DROP_ITEM = 4,
	DOTA_CLICK_BEHAVIOR_DROP_SHOP_ITEM = 5,
	DOTA_CLICK_BEHAVIOR_DRAG = 6,
	DOTA_CLICK_BEHAVIOR_LEARN_ABILITY = 7,
	DOTA_CLICK_BEHAVIOR_LAST = 8,
};

enum class Class_T : unsigned long
{
	CLASS_NONE = 0,
	CLASS_PLAYER = 1,
	CLASS_PLAYER_ALLY = 2,
	LAST_SHARED_ENTITY_CLASS = 3,
};

enum class ConstraintType_t : unsigned long
{
	CONSTRAINT_TYPE_INVALID = 0,
	CONSTRAINT_TYPE_HELPER_BONE = 1,
	CONSTRAINT_TYPE_TWIST = 2,
	CONSTRAINT_TYPE_AIM = 3,
	CONSTRAINT_TYPE_POINT = 4,
	CONSTRAINT_TYPE_ROTATION = 5,
	CONSTRAINT_TYPE_ORIENT = 6,
	CONSTRAINT_TYPE_2_BONE_IK = 7,
	CONSTRAINT_TYPE_JIGGLE_BONE = 8,
	CONSTRAINT_TYPE_MAX = 9,
};

enum class CourierState_t : signed long
{
	COURIER_STATE_INIT = -1,
	COURIER_STATE_IDLE = 0,
	COURIER_STATE_AT_BASE = 1,
	COURIER_STATE_MOVING = 2,
	COURIER_STATE_DELIVERING_ITEMS = 3,
	COURIER_STATE_RETURNING_TO_BASE = 4,
	COURIER_STATE_DEAD = 5,
	COURIER_NUM_STATES = 6,
};

enum class CreatureAbilityType : unsigned long
{
	CREATURE_ABILITY_OFFENSIVE = 0,
	CREATURE_ABILITY_DEFENSIVE = 1,
	CREATURE_ABILITY_ESCAPE = 2,
};

enum class CubeMapFace_t : unsigned long
{
	CUBEMAP_FACE_POSITIVE_X = 0,
	CUBEMAP_FACE_NEGATIVE_X = 1,
	CUBEMAP_FACE_POSITIVE_Y = 2,
	CUBEMAP_FACE_NEGATIVE_Y = 3,
	CUBEMAP_FACE_POSITIVE_Z = 4,
	CUBEMAP_FACE_NEGATIVE_Z = 5,
};

enum class DAMAGE_TYPES : unsigned long
{
	DAMAGE_TYPE_NONE = 0,
	DAMAGE_TYPE_PHYSICAL = 1,
	DAMAGE_TYPE_MAGICAL = 2,
	DAMAGE_TYPE_PURE = 4,
	DAMAGE_TYPE_HP_REMOVAL = 8,
	DAMAGE_TYPE_ALL = 7,
};

enum class DOTAAbilitySpeakTrigger_t : unsigned long
{
	DOTA_ABILITY_SPEAK_START_ACTION_PHASE = 0,
	DOTA_ABILITY_SPEAK_CAST = 1,
};

enum class DOTADamageFlag_t : unsigned long
{
	DOTA_DAMAGE_FLAG_NONE = 0,
	DOTA_DAMAGE_FLAG_IGNORES_MAGIC_ARMOR = 1,
	DOTA_DAMAGE_FLAG_IGNORES_PHYSICAL_ARMOR = 2,
	DOTA_DAMAGE_FLAG_BYPASSES_INVULNERABILITY = 4,
	DOTA_DAMAGE_FLAG_BYPASSES_BLOCK = 8,
	DOTA_DAMAGE_FLAG_REFLECTION = 16,
	DOTA_DAMAGE_FLAG_HPLOSS = 32,
	DOTA_DAMAGE_FLAG_NO_DIRECTOR_EVENT = 64,
	DOTA_DAMAGE_FLAG_NON_LETHAL = 128,
	DOTA_DAMAGE_FLAG_USE_COMBAT_PROFICIENCY = 256,
	DOTA_DAMAGE_FLAG_NO_DAMAGE_MULTIPLIERS = 512,
};

enum class DOTAHUDVisibility_t : unsigned long
{
	DOTA_HUD_VISIBILITY_TOP_TIMEOFDAY = 0,
	DOTA_HUD_VISIBILITY_TOP_HEROES = 1,
	DOTA_HUD_VISIBILITY_TOP_SCOREBOARD = 2,
	DOTA_HUD_VISIBILITY_ACTION_PANEL = 3,
	DOTA_HUD_VISIBILITY_ACTION_MINIMAP = 4,
	DOTA_HUD_VISIBILITY_INVENTORY_PANEL = 5,
	DOTA_HUD_VISIBILITY_INVENTORY_SHOP = 6,
	DOTA_HUD_VISIBILITY_INVENTORY_ITEMS = 7,
	DOTA_HUD_VISIBILITY_INVENTORY_QUICKBUY = 8,
	DOTA_HUD_VISIBILITY_INVENTORY_COURIER = 9,
	DOTA_HUD_VISIBILITY_INVENTORY_PROTECT = 10,
	DOTA_HUD_VISIBILITY_INVENTORY_GOLD = 11,
	DOTA_HUD_VISIBILITY_SHOP_SUGGESTEDITEMS = 12,
	DOTA_HUD_VISIBILITY_COUNT = 13,
};

enum class DOTAInventoryFlags_t : unsigned long
{
	DOTA_INVENTORY_ALLOW_NONE = 0,
	DOTA_INVENTORY_ALLOW_MAIN = 1,
	DOTA_INVENTORY_ALLOW_STASH = 2,
	DOTA_INVENTORY_ALLOW_DROP_ON_GROUND = 4,
	DOTA_INVENTORY_ALLOW_DROP_AT_FOUNTAIN = 8,
	DOTA_INVENTORY_LIMIT_DROP_ON_GROUND = 16,
	DOTA_INVENTORY_ALL_ACCESS = 3,
};

enum class DOTALimits_t : unsigned long
{
	DOTA_MAX_PLAYERS = 64,
	DOTA_MAX_TEAM = 5,
	DOTA_MAX_PLAYER_TEAMS = 10,
	DOTA_MAX_TEAM_PLAYERS = 10,
};

enum class DOTAMinimapEvent_t : unsigned long
{
	DOTA_MINIMAP_EVENT_ANCIENT_UNDER_ATTACK = 2,
	DOTA_MINIMAP_EVENT_BASE_UNDER_ATTACK = 4,
	DOTA_MINIMAP_EVENT_BASE_GLYPHED = 8,
	DOTA_MINIMAP_EVENT_TEAMMATE_UNDER_ATTACK = 16,
	DOTA_MINIMAP_EVENT_TEAMMATE_TELEPORTING = 32,
	DOTA_MINIMAP_EVENT_TEAMMATE_DIED = 64,
	DOTA_MINIMAP_EVENT_TUTORIAL_TASK_ACTIVE = 128,
	DOTA_MINIMAP_EVENT_TUTORIAL_TASK_FINISHED = 256,
	DOTA_MINIMAP_EVENT_HINT_LOCATION = 512,
	DOTA_MINIMAP_EVENT_ENEMY_TELEPORTING = 1024,
	DOTA_MINIMAP_EVENT_CANCEL_TELEPORTING = 2048,
};

enum class DOTAModifierAttribute_t : unsigned long
{
	MODIFIER_ATTRIBUTE_NONE = 0,
	MODIFIER_ATTRIBUTE_PERMANENT = 1,
	MODIFIER_ATTRIBUTE_MULTIPLE = 2,
	MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE = 4,
};

enum class DOTAMusicStatus_t : unsigned long
{
	DOTA_MUSIC_STATUS_NONE = 0,
	DOTA_MUSIC_STATUS_EXPLORATION = 1,
	DOTA_MUSIC_STATUS_BATTLE = 2,
	DOTA_MUSIC_STATUS_PRE_GAME_EXPLORATION = 3,
	DOTA_MUSIC_STATUS_DEAD = 4,
	DOTA_MUSIC_STATUS_LAST = 5,
};

enum class DOTAScriptInventorySlot_t : unsigned long
{
	DOTA_ITEM_SLOT_1 = 0,
	DOTA_ITEM_SLOT_2 = 1,
	DOTA_ITEM_SLOT_3 = 2,
	DOTA_ITEM_SLOT_4 = 3,
	DOTA_ITEM_SLOT_5 = 4,
	DOTA_ITEM_SLOT_6 = 5,
	DOTA_STASH_SLOT_1 = 6,
	DOTA_STASH_SLOT_2 = 7,
	DOTA_STASH_SLOT_3 = 8,
	DOTA_STASH_SLOT_4 = 9,
	DOTA_STASH_SLOT_5 = 10,
	DOTA_STASH_SLOT_6 = 11,
};

enum class DOTASlotType_t : signed long
{
	DOTA_LOADOUT_TYPE_INVALID = -1,
	DOTA_LOADOUT_TYPE_WEAPON = 0,
	DOTA_LOADOUT_TYPE_OFFHAND_WEAPON = 1,
	DOTA_LOADOUT_TYPE_WEAPON2 = 2,
	DOTA_LOADOUT_TYPE_OFFHAND_WEAPON2 = 3,
	DOTA_LOADOUT_TYPE_HEAD = 4,
	DOTA_LOADOUT_TYPE_SHOULDER = 5,
	DOTA_LOADOUT_TYPE_ARMS = 6,
	DOTA_LOADOUT_TYPE_ARMOR = 7,
	DOTA_LOADOUT_TYPE_BELT = 8,
	DOTA_LOADOUT_TYPE_NECK = 9,
	DOTA_LOADOUT_TYPE_BACK = 10,
	DOTA_LOADOUT_TYPE_LEGS = 11,
	DOTA_LOADOUT_TYPE_GLOVES = 12,
	DOTA_LOADOUT_TYPE_TAIL = 13,
	DOTA_LOADOUT_TYPE_MISC = 14,
	DOTA_LOADOUT_TYPE_BODY_HEAD = 15,
	DOTA_LOADOUT_TYPE_MOUNT = 16,
	DOTA_LOADOUT_TYPE_SUMMON = 17,
	DOTA_LOADOUT_TYPE_SHAPESHIFT = 18,
	DOTA_LOADOUT_TYPE_TAUNT = 19,
	DOTA_LOADOUT_TYPE_AMBIENT_EFFECTS = 20,
	DOTA_LOADOUT_TYPE_ABILITY_ATTACK = 21,
	DOTA_LOADOUT_TYPE_ABILITY1 = 22,
	DOTA_LOADOUT_TYPE_ABILITY2 = 23,
	DOTA_LOADOUT_TYPE_ABILITY3 = 24,
	DOTA_LOADOUT_TYPE_ABILITY4 = 25,
	DOTA_LOADOUT_TYPE_ABILITY_ULTIMATE = 26,
	DOTA_LOADOUT_TYPE_VOICE = 27,
	DOTA_LOADOUT_TYPE_ACTION_ITEM = 28,
	DOTA_LOADOUT_TYPE_COURIER = 29,
	DOTA_LOADOUT_TYPE_ANNOUNCER = 30,
	DOTA_LOADOUT_TYPE_MEGA_KILLS = 31,
	DOTA_LOADOUT_TYPE_MUSIC = 32,
	DOTA_LOADOUT_TYPE_WARD = 33,
	DOTA_LOADOUT_TYPE_HUD_SKIN = 34,
	DOTA_LOADOUT_TYPE_LOADING_SCREEN = 35,
	DOTA_LOADOUT_TYPE_WEATHER = 36,
	DOTA_LOADOUT_TYPE_HEROIC_STATUE = 37,
	DOTA_LOADOUT_TYPE_MULTIKILL_BANNER = 38,
	DOTA_LOADOUT_TYPE_CURSOR_PACK = 39,
	DOTA_LOADOUT_TYPE_TELEPORT_EFFECT = 40,
	DOTA_LOADOUT_TYPE_BLINK_EFFECT = 41,
	DOTA_LOADOUT_TYPE_TEAM_SHOWCASE = 42,
	DOTA_PLAYER_LOADOUT_START = 28,
	DOTA_PLAYER_LOADOUT_END = 42,
	DOTA_LOADOUT_TYPE_NONE = 43,
	DOTA_LOADOUT_TYPE_COUNT = 44,
};

enum class DOTASpeechType_t : unsigned long
{
	DOTA_SPEECH_USER_INVALID = 0,
	DOTA_SPEECH_USER_SINGLE = 1,
	DOTA_SPEECH_USER_TEAM = 2,
	DOTA_SPEECH_USER_TEAM_NEARBY = 3,
	DOTA_SPEECH_USER_NEARBY = 4,
	DOTA_SPEECH_USER_ALL = 5,
	DOTA_SPEECH_GOOD_TEAM = 6,
	DOTA_SPEECH_BAD_TEAM = 7,
	DOTA_SPEECH_SPECTATOR = 8,
	DOTA_SPEECH_RECIPIENT_TYPE_MAX = 9,
};

enum class DOTATeam_t : unsigned long
{
	DOTA_TEAM_FIRST = 2,
	DOTA_TEAM_GOODGUYS = 2,
	DOTA_TEAM_BADGUYS = 3,
	DOTA_TEAM_NEUTRALS = 4,
	DOTA_TEAM_NOTEAM = 5,
	DOTA_TEAM_CUSTOM_1 = 6,
	DOTA_TEAM_CUSTOM_2 = 7,
	DOTA_TEAM_CUSTOM_3 = 8,
	DOTA_TEAM_CUSTOM_4 = 9,
	DOTA_TEAM_CUSTOM_5 = 10,
	DOTA_TEAM_CUSTOM_6 = 11,
	DOTA_TEAM_CUSTOM_7 = 12,
	DOTA_TEAM_CUSTOM_8 = 13,
	DOTA_TEAM_COUNT = 14,
	DOTA_TEAM_CUSTOM_MIN = 6,
	DOTA_TEAM_CUSTOM_MAX = 13,
	DOTA_TEAM_CUSTOM_COUNT = 8,
};

enum class DOTAUnitAttackCapability_t : unsigned long
{
	DOTA_UNIT_CAP_NO_ATTACK = 0,
	DOTA_UNIT_CAP_MELEE_ATTACK = 1,
	DOTA_UNIT_CAP_RANGED_ATTACK = 2,
};

enum class DOTAUnitMoveCapability_t : unsigned long
{
	DOTA_UNIT_CAP_MOVE_NONE = 0,
	DOTA_UNIT_CAP_MOVE_GROUND = 1,
	DOTA_UNIT_CAP_MOVE_FLY = 2,
};

enum class DOTA_ABILITY_BEHAVIOR : unsigned long
{
	DOTA_ABILITY_BEHAVIOR_NONE = 0,
	DOTA_ABILITY_BEHAVIOR_HIDDEN = 1,
	DOTA_ABILITY_BEHAVIOR_PASSIVE = 2,
	DOTA_ABILITY_BEHAVIOR_NO_TARGET = 4,
	DOTA_ABILITY_BEHAVIOR_UNIT_TARGET = 8,
	DOTA_ABILITY_BEHAVIOR_POINT = 16,
	DOTA_ABILITY_BEHAVIOR_AOE = 32,
	DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE = 64,
	DOTA_ABILITY_BEHAVIOR_CHANNELLED = 128,
	DOTA_ABILITY_BEHAVIOR_ITEM = 256,
	DOTA_ABILITY_BEHAVIOR_TOGGLE = 512,
	DOTA_ABILITY_BEHAVIOR_DIRECTIONAL = 1024,
	DOTA_ABILITY_BEHAVIOR_IMMEDIATE = 2048,
	DOTA_ABILITY_BEHAVIOR_AUTOCAST = 4096,
	DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET = 8192,
	DOTA_ABILITY_BEHAVIOR_OPTIONAL_POINT = 16384,
	DOTA_ABILITY_BEHAVIOR_OPTIONAL_NO_TARGET = 32768,
	DOTA_ABILITY_BEHAVIOR_AURA = 65536,
	DOTA_ABILITY_BEHAVIOR_ATTACK = 131072,
	DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT = 262144,
	DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES = 524288,
	DOTA_ABILITY_BEHAVIOR_UNRESTRICTED = 1048576,
	DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE = 2097152,
	DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL = 4194304,
	DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_MOVEMENT = 8388608,
	DOTA_ABILITY_BEHAVIOR_DONT_ALERT_TARGET = 16777216,
	DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK = 33554432,
	DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN = 67108864,
	DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING = 134217728,
	DOTA_ABILITY_BEHAVIOR_RUNE_TARGET = 268435456,
	DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL = 536870912,
	DOTA_ABILITY_LAST_BEHAVIOR = 536870912,
};

enum class DOTA_HOLDOUT_TOWER_TYPE : unsigned long
{
	DOTA_HOLDOUT_TOWER_NONE = 0,
	DOTA_HOLDOUT_TOWER_LIGHTFAST = 1,
	DOTA_HOLDOUT_TOWER_HEAVYSLOW = 2,
	DOTA_HOLDOUT_TOWER_REDUCESPEED = 3,
	DOTA_HOLDOUT_TOWER_COUNT = 4,
};

enum class DOTA_HOLDOUT_WALL_TYPE : unsigned long
{
	DOTA_HOLDOUT_WALL_NONE = 0,
	DOTA_HOLDOUT_WALL_PHYSICAL = 1,
	DOTA_HOLDOUT_WALL_FIRE = 2,
	DOTA_HOLDOUT_WALL_ICE = 3,
	DOTA_HOLDOUT_WALL_COUNT = 4,
};

enum class DOTA_HeroPickState : unsigned long
{
	DOTA_HEROPICK_STATE_NONE = 0,
	DOTA_HEROPICK_STATE_AP_SELECT = 1,
	DOTA_HEROPICK_STATE_SD_SELECT = 2,
	DOTA_HEROPICK_STATE_INTRO_SELECT = 3,
	DOTA_HEROPICK_STATE_RD_SELECT = 4,
	DOTA_HEROPICK_STATE_CM_INTRO = 5,
	DOTA_HEROPICK_STATE_CM_CAPTAINPICK = 6,
	DOTA_HEROPICK_STATE_CM_BAN1 = 7,
	DOTA_HEROPICK_STATE_CM_BAN2 = 8,
	DOTA_HEROPICK_STATE_CM_BAN3 = 9,
	DOTA_HEROPICK_STATE_CM_BAN4 = 10,
	DOTA_HEROPICK_STATE_CM_BAN5 = 11,
	DOTA_HEROPICK_STATE_CM_BAN6 = 12,
	DOTA_HEROPICK_STATE_CM_BAN7 = 13,
	DOTA_HEROPICK_STATE_CM_BAN8 = 14,
	DOTA_HEROPICK_STATE_CM_BAN9 = 15,
	DOTA_HEROPICK_STATE_CM_BAN10 = 16,
	DOTA_HEROPICK_STATE_CM_SELECT1 = 17,
	DOTA_HEROPICK_STATE_CM_SELECT2 = 18,
	DOTA_HEROPICK_STATE_CM_SELECT3 = 19,
	DOTA_HEROPICK_STATE_CM_SELECT4 = 20,
	DOTA_HEROPICK_STATE_CM_SELECT5 = 21,
	DOTA_HEROPICK_STATE_CM_SELECT6 = 22,
	DOTA_HEROPICK_STATE_CM_SELECT7 = 23,
	DOTA_HEROPICK_STATE_CM_SELECT8 = 24,
	DOTA_HEROPICK_STATE_CM_SELECT9 = 25,
	DOTA_HEROPICK_STATE_CM_SELECT10 = 26,
	DOTA_HEROPICK_STATE_CM_PICK = 27,
	DOTA_HEROPICK_STATE_AR_SELECT = 28,
	DOTA_HEROPICK_STATE_MO_SELECT = 29,
	DOTA_HEROPICK_STATE_FH_SELECT = 30,
	DOTA_HEROPICK_STATE_CD_INTRO = 31,
	DOTA_HEROPICK_STATE_CD_CAPTAINPICK = 32,
	DOTA_HEROPICK_STATE_CD_BAN1 = 33,
	DOTA_HEROPICK_STATE_CD_BAN2 = 34,
	DOTA_HEROPICK_STATE_CD_BAN3 = 35,
	DOTA_HEROPICK_STATE_CD_BAN4 = 36,
	DOTA_HEROPICK_STATE_CD_BAN5 = 37,
	DOTA_HEROPICK_STATE_CD_BAN6 = 38,
	DOTA_HEROPICK_STATE_CD_SELECT1 = 39,
	DOTA_HEROPICK_STATE_CD_SELECT2 = 40,
	DOTA_HEROPICK_STATE_CD_SELECT3 = 41,
	DOTA_HEROPICK_STATE_CD_SELECT4 = 42,
	DOTA_HEROPICK_STATE_CD_SELECT5 = 43,
	DOTA_HEROPICK_STATE_CD_SELECT6 = 44,
	DOTA_HEROPICK_STATE_CD_SELECT7 = 45,
	DOTA_HEROPICK_STATE_CD_SELECT8 = 46,
	DOTA_HEROPICK_STATE_CD_SELECT9 = 47,
	DOTA_HEROPICK_STATE_CD_SELECT10 = 48,
	DOTA_HEROPICK_STATE_CD_PICK = 49,
	DOTA_HEROPICK_STATE_BD_SELECT = 50,
	DOTA_HERO_PICK_STATE_ABILITY_DRAFT_SELECT = 51,
	DOTA_HERO_PICK_STATE_ARDM_SELECT = 52,
	DOTA_HEROPICK_STATE_ALL_DRAFT_SELECT = 53,
	DOTA_HERO_PICK_STATE_CUSTOMGAME_SELECT = 54,
	DOTA_HEROPICK_STATE_COUNT = 55,
};

enum class DOTA_LANE : unsigned long
{
	DOTA_LANE_NONE = 0,
	DOTA_LANE_TOP = 1,
	DOTA_LANE_MIDDLE = 2,
	DOTA_LANE_BOTTOM = 3,
	DOTA_LANE_MAX = 4,
};

enum class DOTA_MOTION_CONTROLLER_PRIORITY : unsigned long
{
	DOTA_MOTION_CONTROLLER_PRIORITY_LOWEST = 0,
	DOTA_MOTION_CONTROLLER_PRIORITY_LOW = 1,
	DOTA_MOTION_CONTROLLER_PRIORITY_MEDIUM = 2,
	DOTA_MOTION_CONTROLLER_PRIORITY_HIGH = 3,
	DOTA_MOTION_CONTROLLER_PRIORITY_HIGHEST = 4,
};

enum class DOTA_RUNES : signed long
{
	DOTA_RUNE_INVALID = -1,
	DOTA_RUNE_DOUBLEDAMAGE = 0,
	DOTA_RUNE_HASTE = 1,
	DOTA_RUNE_ILLUSION = 2,
	DOTA_RUNE_INVISIBILITY = 3,
	DOTA_RUNE_REGENERATION = 4,
	DOTA_RUNE_BOUNTY = 5,
	DOTA_RUNE_COUNT = 6,
	DOTA_RUNE_HAUNTED = 7,
	DOTA_RUNE_SPOOKY = 8,
	DOTA_RUNE_RAPIER = 9,
	DOTA_RUNE_TURBO = 10,
	DOTA_RUNE_MYSTERY = 11,
	DOTA_HALLOWEEN_RUNE_COUNT = 12,
};

enum class DOTA_SHOP_TYPE : unsigned long
{
	DOTA_SHOP_HOME = 0,
	DOTA_SHOP_SIDE = 1,
	DOTA_SHOP_SECRET = 2,
	DOTA_SHOP_GROUND = 3,
	DOTA_SHOP_SIDE2 = 4,
	DOTA_SHOP_SECRET2 = 5,
	DOTA_SHOP_NONE = 6,
};

enum class DOTA_UNIT_TARGET_FLAGS : unsigned long
{
	DOTA_UNIT_TARGET_FLAG_NONE = 0,
	DOTA_UNIT_TARGET_FLAG_RANGED_ONLY = 2,
	DOTA_UNIT_TARGET_FLAG_MELEE_ONLY = 4,
	DOTA_UNIT_TARGET_FLAG_DEAD = 8,
	DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES = 16,
	DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES = 32,
	DOTA_UNIT_TARGET_FLAG_INVULNERABLE = 64,
	DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE = 128,
	DOTA_UNIT_TARGET_FLAG_NO_INVIS = 256,
	DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS = 512,
	DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED = 1024,
	DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED = 2048,
	DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED = 4096,
	DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS = 8192,
	DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE = 16384,
	DOTA_UNIT_TARGET_FLAG_MANA_ONLY = 32768,
	DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP = 65536,
	DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO = 131072,
	DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD = 262144,
	DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED = 524288,
};

enum class DOTA_UNIT_TARGET_TEAM : unsigned long
{
	DOTA_UNIT_TARGET_TEAM_NONE = 0,
	DOTA_UNIT_TARGET_TEAM_FRIENDLY = 1,
	DOTA_UNIT_TARGET_TEAM_ENEMY = 2,
	DOTA_UNIT_TARGET_TEAM_CUSTOM = 4,
	DOTA_UNIT_TARGET_TEAM_BOTH = 3,
};

enum class DOTA_UNIT_TARGET_TYPE : unsigned long
{
	DOTA_UNIT_TARGET_NONE = 0,
	DOTA_UNIT_TARGET_HERO = 1,
	DOTA_UNIT_TARGET_CREEP = 2,
	DOTA_UNIT_TARGET_BUILDING = 4,
	DOTA_UNIT_TARGET_MECHANICAL = 8,
	DOTA_UNIT_TARGET_COURIER = 16,
	DOTA_UNIT_TARGET_OTHER = 32,
	DOTA_UNIT_TARGET_TREE = 64,
	DOTA_UNIT_TARGET_CUSTOM = 128,
	DOTA_UNIT_TARGET_BASIC = 18,
	DOTA_UNIT_TARGET_ALL = 63,
};

enum class DamageOptions_t : unsigned char
{
	DAMAGE_NO = 0,
	DAMAGE_EVENTS_ONLY = 1,
	DAMAGE_YES = 2,
};

enum class Disposition_t : unsigned long
{
	D_ER = 0,
	D_HT = 1,
	D_FR = 2,
	D_LI = 3,
	D_NU = 4,
	D_ERROR = 0,
	D_HATE = 1,
	D_FEAR = 2,
	D_LIKE = 3,
	D_NEUTRAL = 4,
};

enum class DoorState_t : unsigned long
{
	DOOR_STATE_CLOSED = 0,
	DOOR_STATE_OPENING = 1,
	DOOR_STATE_OPEN = 2,
	DOOR_STATE_CLOSING = 3,
	DOOR_STATE_AJAR = 4,
};

enum class DotaCustomUIType_t : signed long
{
	DOTA_CUSTOM_UI_TYPE_HUD = 0,
	DOTA_CUSTOM_UI_TYPE_HERO_SELECTION = 1,
	DOTA_CUSTOM_UI_TYPE_GAME_INFO = 2,
	DOTA_CUSTOM_UI_TYPE_GAME_SETUP = 3,
	DOTA_CUSTOM_UI_TYPE_FLYOUT_SCOREBOARD = 4,
	DOTA_CUSTOM_UI_TYPE_HUD_TOP_BAR = 5,
	DOTA_CUSTOM_UI_TYPE_END_SCREEN = 6,
	DOTA_CUSTOM_UI_TYPE_COUNT = 7,
	DOTA_CUSTOM_UI_TYPE_INVALID = -1,
};

enum class DotaDefaultUIElement_t : unsigned long
{
	DOTA_DEFAULT_UI_TOP_TIMEOFDAY = 0,
	DOTA_DEFAULT_UI_TOP_HEROES = 1,
	DOTA_DEFAULT_UI_FLYOUT_SCOREBOARD = 2,
	DOTA_DEFAULT_UI_ACTION_PANEL = 3,
	DOTA_DEFAULT_UI_ACTION_MINIMAP = 4,
	DOTA_DEFAULT_UI_INVENTORY_PANEL = 5,
	DOTA_DEFAULT_UI_INVENTORY_SHOP = 6,
	DOTA_DEFAULT_UI_INVENTORY_ITEMS = 7,
	DOTA_DEFAULT_UI_INVENTORY_QUICKBUY = 8,
	DOTA_DEFAULT_UI_INVENTORY_COURIER = 9,
	DOTA_DEFAULT_UI_INVENTORY_PROTECT = 10,
	DOTA_DEFAULT_UI_INVENTORY_GOLD = 11,
	DOTA_DEFAULT_UI_SHOP_SUGGESTEDITEMS = 12,
	DOTA_DEFAULT_UI_HERO_SELECTION_TEAMS = 13,
	DOTA_DEFAULT_UI_HERO_SELECTION_GAME_NAME = 14,
	DOTA_DEFAULT_UI_HERO_SELECTION_CLOCK = 15,
	DOTA_DEFAULT_UI_TOP_MENU_BUTTONS = 16,
	DOTA_DEFAULT_UI_TOP_BAR_BACKGROUND = 17,
	DOTA_DEFAULT_UI_ENDGAME = 18,
	DOTA_DEFAULT_UI_ELEMENT_COUNT = 19,
};

enum class ECNYBeastAbility : unsigned long
{
	ECNYBeastAbility_Path_Support = 0,
	ECNYBeastAbility_Path_Combat = 1,
	ECNYBeastAbility_Path_Speed = 2,
	ECNYBeastAbility_Aura_AttackSpeed = 3,
	ECNYBeastAbility_Aura_MoveSpeed = 4,
	ECNYBeastAbility_Aura_Heal = 5,
	ECNYBeastAbility_Buff_CriticalStrike = 6,
	ECNYBeastAbility_Buff_Bash = 7,
	ECNYBeastAbility_Buff_Cleave = 8,
	ECNYBeastAbility_Active_SonicWave = 9,
	ECNYBeastAbility_Active_BlackHole = 10,
	ECNYBeastAbility_Active_Chronosphere = 11,
	ECNYBeastAbility_Invalid = 12,
};

enum class EDOTA_ModifyGold_Reason : unsigned long
{
	DOTA_ModifyGold_Unspecified = 0,
	DOTA_ModifyGold_Death = 1,
	DOTA_ModifyGold_Buyback = 2,
	DOTA_ModifyGold_PurchaseConsumable = 3,
	DOTA_ModifyGold_PurchaseItem = 4,
	DOTA_ModifyGold_AbandonedRedistribute = 5,
	DOTA_ModifyGold_SellItem = 6,
	DOTA_ModifyGold_AbilityCost = 7,
	DOTA_ModifyGold_CheatCommand = 8,
	DOTA_ModifyGold_SelectionPenalty = 9,
	DOTA_ModifyGold_GameTick = 10,
	DOTA_ModifyGold_Building = 11,
	DOTA_ModifyGold_HeroKill = 12,
	DOTA_ModifyGold_CreepKill = 13,
	DOTA_ModifyGold_RoshanKill = 14,
	DOTA_ModifyGold_CourierKill = 15,
	DOTA_ModifyGold_SharedGold = 16,
};

enum class EDOTA_ModifyXP_Reason : unsigned long
{
	DOTA_ModifyXP_Unspecified = 0,
	DOTA_ModifyXP_HeroKill = 1,
	DOTA_ModifyXP_CreepKill = 2,
	DOTA_ModifyXP_RoshanKill = 3,
};

enum class ERenderDepthMode : unsigned long
{
	DEPTH_MODE_NORMAL = 0,
	DEPTH_MODE_SHADOW = 1,
	DEPTH_MODE_SSA0 = 2,
	DEPTH_MODE_MAX = 3,
};

enum class EShareAbility : unsigned long
{
	ITEM_FULLY_SHAREABLE = 0,
	ITEM_PARTIALLY_SHAREABLE = 1,
	ITEM_NOT_SHAREABLE = 2,
};

enum class EShowcaseEditorMode : unsigned long
{
	SCEM_DEFAULT = 0,
	SCEM_POSITIONING_SHOWCASE = 1,
	SCEM_SELECTING_CAMERA_ANIMATION = 2,
	SCEM_POSITIONING_SLOT = 3,
	SCEM_PREVIEWING_SHOWCASE = 4,
};

enum class ETeamShowcase_SlotType : signed long
{
	ETeamShowcase_SlotType_Invalid = -1,
	ETeamShowcase_SlotType_Empty = 0,
	ETeamShowcase_SlotType_Hero = 1,
	ETeamShowcase_SlotType_EconItem_Effigy = 2,
	ETeamShowcase_SlotType_EconItem_Wearable = 3,
	ETeamShowcase_SlotType_EconItem_Courier = 4,
	ETeamShowcase_SlotType_Fixed_Start = 5,
	ETeamShowcase_SlotType_CameraAnimation = 5,
	ETeamShowcase_SlotType_Music = 6,
	ETeamShowcase_SlotType_VO = 7,
	ETeamShowcase_SlotType_Fixed_Last = 7,
	ETeamShowcase_SlotType_NUM_TYPES = 8,
};

enum class EntFinderMethod_t : unsigned long
{
	ENT_FIND_METHOD_NEAREST = 0,
	ENT_FIND_METHOD_FARTHEST = 1,
	ENT_FIND_METHOD_RANDOM = 2,
};

enum class EntityDisolveType_t : unsigned long
{
	ENTITY_DISSOLVE_NORMAL = 0,
	ENTITY_DISSOLVE_ELECTRICAL = 1,
	ENTITY_DISSOLVE_ELECTRICAL_LIGHT = 2,
	ENTITY_DISSOLVE_CORE = 3,
};

enum class EntityDormancyType_t : unsigned long
{
	ENTITY_NOT_DORMANT = 0,
	ENTITY_DORMANT = 1,
	ENTITY_SUSPENDED = 2,
};

enum class EntityIOTargetType_t : signed long
{
	ENTITY_IO_TARGET_INVALID = -1,
	ENTITY_IO_TARGET_CLASSNAME = 0,
	ENTITY_IO_TARGET_CLASSNAME_DERIVES_FROM = 1,
	ENTITY_IO_TARGET_ENTITYNAME = 2,
	ENTITY_IO_TARGET_CONTAINS_COMPONENT = 3,
	ENTITY_IO_TARGET_SPECIAL_ACTIVATOR = 4,
	ENTITY_IO_TARGET_SPECIAL_CALLER = 5,
	ENTITY_IO_TARGET_EHANDLE = 6,
	ENTITY_IO_TARGET_ENTITYNAME_OR_CLASSNAME = 7,
};

enum class EntityLumpFlags_t : unsigned long
{
	ENTITY_LUMP_NONE = 0,
};

enum class Explosions : unsigned long
{
	expRandom = 0,
	expDirected = 1,
	expUsePrecise = 2,
};

enum class FuncDoorSpawnPos_t : unsigned long
{
	FUNC_DOOR_SPAWN_CLOSED = 0,
	FUNC_DOOR_SPAWN_OPEN = 1,
};

enum class GameActivity_t : unsigned long
{
	ACT_DOTA_IDLE = 1500,
	ACT_DOTA_IDLE_RARE = 1501,
	ACT_DOTA_RUN = 1502,
	ACT_DOTA_ATTACK = 1503,
	ACT_DOTA_ATTACK2 = 1504,
	ACT_DOTA_ATTACK_EVENT = 1505,
	ACT_DOTA_DIE = 1506,
	ACT_DOTA_FLINCH = 1507,
	ACT_DOTA_FLAIL = 1508,
	ACT_DOTA_DISABLED = 1509,
	ACT_DOTA_CAST_ABILITY_1 = 1510,
	ACT_DOTA_CAST_ABILITY_2 = 1511,
	ACT_DOTA_CAST_ABILITY_3 = 1512,
	ACT_DOTA_CAST_ABILITY_4 = 1513,
	ACT_DOTA_CAST_ABILITY_5 = 1514,
	ACT_DOTA_CAST_ABILITY_6 = 1515,
	ACT_DOTA_OVERRIDE_ABILITY_1 = 1516,
	ACT_DOTA_OVERRIDE_ABILITY_2 = 1517,
	ACT_DOTA_OVERRIDE_ABILITY_3 = 1518,
	ACT_DOTA_OVERRIDE_ABILITY_4 = 1519,
	ACT_DOTA_CHANNEL_ABILITY_1 = 1520,
	ACT_DOTA_CHANNEL_ABILITY_2 = 1521,
	ACT_DOTA_CHANNEL_ABILITY_3 = 1522,
	ACT_DOTA_CHANNEL_ABILITY_4 = 1523,
	ACT_DOTA_CHANNEL_ABILITY_5 = 1524,
	ACT_DOTA_CHANNEL_ABILITY_6 = 1525,
	ACT_DOTA_CHANNEL_END_ABILITY_1 = 1526,
	ACT_DOTA_CHANNEL_END_ABILITY_2 = 1527,
	ACT_DOTA_CHANNEL_END_ABILITY_3 = 1528,
	ACT_DOTA_CHANNEL_END_ABILITY_4 = 1529,
	ACT_DOTA_CHANNEL_END_ABILITY_5 = 1530,
	ACT_DOTA_CHANNEL_END_ABILITY_6 = 1531,
	ACT_DOTA_CONSTANT_LAYER = 1532,
	ACT_DOTA_CAPTURE = 1533,
	ACT_DOTA_SPAWN = 1534,
	ACT_DOTA_KILLTAUNT = 1535,
	ACT_DOTA_TAUNT = 1536,
	ACT_DOTA_THIRST = 1537,
	ACT_DOTA_CAST_DRAGONBREATH = 1538,
	ACT_DOTA_ECHO_SLAM = 1539,
	ACT_DOTA_CAST_ABILITY_1_END = 1540,
	ACT_DOTA_CAST_ABILITY_2_END = 1541,
	ACT_DOTA_CAST_ABILITY_3_END = 1542,
	ACT_DOTA_CAST_ABILITY_4_END = 1543,
	ACT_MIRANA_LEAP_END = 1544,
	ACT_WAVEFORM_START = 1545,
	ACT_WAVEFORM_END = 1546,
	ACT_DOTA_CAST_ABILITY_ROT = 1547,
	ACT_DOTA_DIE_SPECIAL = 1548,
	ACT_DOTA_RATTLETRAP_BATTERYASSAULT = 1549,
	ACT_DOTA_RATTLETRAP_POWERCOGS = 1550,
	ACT_DOTA_RATTLETRAP_HOOKSHOT_START = 1551,
	ACT_DOTA_RATTLETRAP_HOOKSHOT_LOOP = 1552,
	ACT_DOTA_RATTLETRAP_HOOKSHOT_END = 1553,
	ACT_STORM_SPIRIT_OVERLOAD_RUN_OVERRIDE = 1554,
	ACT_DOTA_TINKER_REARM1 = 1555,
	ACT_DOTA_TINKER_REARM2 = 1556,
	ACT_DOTA_TINKER_REARM3 = 1557,
	ACT_TINY_AVALANCHE = 1558,
	ACT_TINY_TOSS = 1559,
	ACT_TINY_GROWL = 1560,
	ACT_DOTA_WEAVERBUG_ATTACH = 1561,
	ACT_DOTA_CAST_WILD_AXES_END = 1562,
	ACT_DOTA_CAST_LIFE_BREAK_START = 1563,
	ACT_DOTA_CAST_LIFE_BREAK_END = 1564,
	ACT_DOTA_NIGHTSTALKER_TRANSITION = 1565,
	ACT_DOTA_LIFESTEALER_RAGE = 1566,
	ACT_DOTA_LIFESTEALER_OPEN_WOUNDS = 1567,
	ACT_DOTA_SAND_KING_BURROW_IN = 1568,
	ACT_DOTA_SAND_KING_BURROW_OUT = 1569,
	ACT_DOTA_EARTHSHAKER_TOTEM_ATTACK = 1570,
	ACT_DOTA_WHEEL_LAYER = 1571,
	ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_START = 1572,
	ACT_DOTA_ALCHEMIST_CONCOCTION = 1573,
	ACT_DOTA_JAKIRO_LIQUIDFIRE_START = 1574,
	ACT_DOTA_JAKIRO_LIQUIDFIRE_LOOP = 1575,
	ACT_DOTA_LIFESTEALER_INFEST = 1576,
	ACT_DOTA_LIFESTEALER_INFEST_END = 1577,
	ACT_DOTA_LASSO_LOOP = 1578,
	ACT_DOTA_ALCHEMIST_CONCOCTION_THROW = 1579,
	ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_END = 1580,
	ACT_DOTA_CAST_COLD_SNAP = 1581,
	ACT_DOTA_CAST_GHOST_WALK = 1582,
	ACT_DOTA_CAST_TORNADO = 1583,
	ACT_DOTA_CAST_EMP = 1584,
	ACT_DOTA_CAST_ALACRITY = 1585,
	ACT_DOTA_CAST_CHAOS_METEOR = 1586,
	ACT_DOTA_CAST_SUN_STRIKE = 1587,
	ACT_DOTA_CAST_FORGE_SPIRIT = 1588,
	ACT_DOTA_CAST_ICE_WALL = 1589,
	ACT_DOTA_CAST_DEAFENING_BLAST = 1590,
	ACT_DOTA_VICTORY = 1591,
	ACT_DOTA_DEFEAT = 1592,
	ACT_DOTA_SPIRIT_BREAKER_CHARGE_POSE = 1593,
	ACT_DOTA_SPIRIT_BREAKER_CHARGE_END = 1594,
	ACT_DOTA_TELEPORT = 1595,
	ACT_DOTA_TELEPORT_END = 1596,
	ACT_DOTA_CAST_REFRACTION = 1597,
	ACT_DOTA_CAST_ABILITY_7 = 1598,
	ACT_DOTA_CANCEL_SIREN_SONG = 1599,
	ACT_DOTA_CHANNEL_ABILITY_7 = 1600,
	ACT_DOTA_LOADOUT = 1601,
	ACT_DOTA_FORCESTAFF_END = 1602,
	ACT_DOTA_POOF_END = 1603,
	ACT_DOTA_SLARK_POUNCE = 1604,
	ACT_DOTA_MAGNUS_SKEWER_START = 1605,
	ACT_DOTA_MAGNUS_SKEWER_END = 1606,
	ACT_DOTA_MEDUSA_STONE_GAZE = 1607,
	ACT_DOTA_RELAX_START = 1608,
	ACT_DOTA_RELAX_LOOP = 1609,
	ACT_DOTA_RELAX_END = 1610,
	ACT_DOTA_CENTAUR_STAMPEDE = 1611,
	ACT_DOTA_BELLYACHE_START = 1612,
	ACT_DOTA_BELLYACHE_LOOP = 1613,
	ACT_DOTA_BELLYACHE_END = 1614,
	ACT_DOTA_ROQUELAIRE_LAND = 1615,
	ACT_DOTA_ROQUELAIRE_LAND_IDLE = 1616,
	ACT_DOTA_GREEVIL_CAST = 1617,
	ACT_DOTA_GREEVIL_OVERRIDE_ABILITY = 1618,
	ACT_DOTA_GREEVIL_HOOK_START = 1619,
	ACT_DOTA_GREEVIL_HOOK_END = 1620,
	ACT_DOTA_GREEVIL_BLINK_BONE = 1621,
	ACT_DOTA_IDLE_SLEEPING = 1622,
	ACT_DOTA_INTRO = 1623,
	ACT_DOTA_GESTURE_POINT = 1624,
	ACT_DOTA_GESTURE_ACCENT = 1625,
	ACT_DOTA_SLEEPING_END = 1626,
	ACT_DOTA_AMBUSH = 1627,
	ACT_DOTA_ITEM_LOOK = 1628,
	ACT_DOTA_STARTLE = 1629,
	ACT_DOTA_FRUSTRATION = 1630,
	ACT_DOTA_TELEPORT_REACT = 1631,
	ACT_DOTA_TELEPORT_END_REACT = 1632,
	ACT_DOTA_SHRUG = 1633,
	ACT_DOTA_RELAX_LOOP_END = 1634,
	ACT_DOTA_PRESENT_ITEM = 1635,
	ACT_DOTA_IDLE_IMPATIENT = 1636,
	ACT_DOTA_SHARPEN_WEAPON = 1637,
	ACT_DOTA_SHARPEN_WEAPON_OUT = 1638,
	ACT_DOTA_IDLE_SLEEPING_END = 1639,
	ACT_DOTA_BRIDGE_DESTROY = 1640,
	ACT_DOTA_TAUNT_SNIPER = 1641,
	ACT_DOTA_DEATH_BY_SNIPER = 1642,
	ACT_DOTA_LOOK_AROUND = 1643,
	ACT_DOTA_CAGED_CREEP_RAGE = 1644,
	ACT_DOTA_CAGED_CREEP_RAGE_OUT = 1645,
	ACT_DOTA_CAGED_CREEP_SMASH = 1646,
	ACT_DOTA_CAGED_CREEP_SMASH_OUT = 1647,
	ACT_DOTA_IDLE_IMPATIENT_SWORD_TAP = 1648,
	ACT_DOTA_INTRO_LOOP = 1649,
	ACT_DOTA_BRIDGE_THREAT = 1650,
	ACT_DOTA_DAGON = 1651,
	ACT_DOTA_CAST_ABILITY_2_ES_ROLL_START = 1652,
	ACT_DOTA_CAST_ABILITY_2_ES_ROLL = 1653,
	ACT_DOTA_CAST_ABILITY_2_ES_ROLL_END = 1654,
	ACT_DOTA_NIAN_PIN_START = 1655,
	ACT_DOTA_NIAN_PIN_LOOP = 1656,
	ACT_DOTA_NIAN_PIN_END = 1657,
	ACT_DOTA_LEAP_STUN = 1658,
	ACT_DOTA_LEAP_SWIPE = 1659,
	ACT_DOTA_NIAN_INTRO_LEAP = 1660,
	ACT_DOTA_AREA_DENY = 1661,
	ACT_DOTA_NIAN_PIN_TO_STUN = 1662,
	ACT_DOTA_RAZE_1 = 1663,
	ACT_DOTA_RAZE_2 = 1664,
	ACT_DOTA_RAZE_3 = 1665,
	ACT_DOTA_UNDYING_DECAY = 1666,
	ACT_DOTA_UNDYING_SOUL_RIP = 1667,
	ACT_DOTA_UNDYING_TOMBSTONE = 1668,
	ACT_DOTA_WHIRLING_AXES_RANGED = 1669,
	ACT_DOTA_SHALLOW_GRAVE = 1670,
	ACT_DOTA_COLD_FEET = 1671,
	ACT_DOTA_ICE_VORTEX = 1672,
	ACT_DOTA_CHILLING_TOUCH = 1673,
	ACT_DOTA_ENFEEBLE = 1674,
	ACT_DOTA_FATAL_BONDS = 1675,
	ACT_DOTA_MIDNIGHT_PULSE = 1676,
	ACT_DOTA_ANCESTRAL_SPIRIT = 1677,
	ACT_DOTA_THUNDER_STRIKE = 1678,
	ACT_DOTA_KINETIC_FIELD = 1679,
	ACT_DOTA_STATIC_STORM = 1680,
	ACT_DOTA_MINI_TAUNT = 1681,
	ACT_DOTA_ARCTIC_BURN_END = 1682,
	ACT_DOTA_LOADOUT_RARE = 1683,
	ACT_DOTA_SWIM = 1684,
	ACT_DOTA_FLEE = 1685,
	ACT_DOTA_TROT = 1686,
	ACT_DOTA_SHAKE = 1687,
	ACT_DOTA_SWIM_IDLE = 1688,
	ACT_DOTA_WAIT_IDLE = 1689,
	ACT_DOTA_GREET = 1690,
	ACT_DOTA_TELEPORT_COOP_START = 1691,
	ACT_DOTA_TELEPORT_COOP_WAIT = 1692,
	ACT_DOTA_TELEPORT_COOP_END = 1693,
	ACT_DOTA_TELEPORT_COOP_EXIT = 1694,
	ACT_DOTA_SHOPKEEPER_PET_INTERACT = 1695,
	ACT_DOTA_ITEM_PICKUP = 1696,
	ACT_DOTA_ITEM_DROP = 1697,
	ACT_DOTA_CAPTURE_PET = 1698,
	ACT_DOTA_PET_WARD_OBSERVER = 1699,
	ACT_DOTA_PET_WARD_SENTRY = 1700,
	ACT_DOTA_PET_LEVEL = 1701,
	ACT_DOTA_CAST_BURROW_END = 1702,
	ACT_DOTA_LIFESTEALER_ASSIMILATE = 1703,
	ACT_DOTA_LIFESTEALER_EJECT = 1704,
};

enum class GlobalIlluminationMethod_t : unsigned long
{
	GLOBAL_ILLUMINATION_NONE = 0,
	GLOBAL_ILLUMINATION_BAKE = 1,
	GLOBAL_ILLUMINATION_AMBIENT_OCCLUSION = 2,
	GLOBAL_ILLUMINATION_REALTIME_RADIOSITY = 3,
};

enum class HeroPickType : unsigned long
{
	HERO_PICK = 0,
	HERO_BAN = 1,
};

enum class HierarchyType_t : unsigned long
{
	HIERARCHY_NONE = 0,
	HIERARCHY_BONE_MERGE = 1,
	HIERARCHY_ATTACHMENT = 2,
	HIERARCHY_ABSORIGIN = 3,
	HIERARCHY_BONE = 4,
	HIERARCHY_TYPE_COUNT = 5,
};

enum class HorizJustification_e : unsigned long
{
	HORIZ_JUSTIFICATION_LEFT = 0,
	HORIZ_JUSTIFICATION_CENTER = 1,
	HORIZ_JUSTIFICATION_RIGHT = 2,
	HORIZ_JUSTIFICATION_NONE = 3,
};

enum class Hull_t : unsigned long
{
	HULL_HUMAN = 0,
	HULL_SMALL_CENTERED = 1,
	HULL_WIDE_HUMAN = 2,
	HULL_TINY = 3,
	HULL_MEDIUM = 4,
	HULL_TINY_CENTERED = 5,
	HULL_LARGE = 6,
	HULL_LARGE_CENTERED = 7,
	HULL_MEDIUM_TALL = 8,
	NUM_HULLS = 9,
	HULL_NONE = 10,
};

enum class IGE_AssassinationState : unsigned long
{
	ASSASSINMINIGAMESTATE_NotActive = 0,
	ASSASSINMINIGAMESTATE_AwaitingInitialization = 1,
	ASSASSINMINIGAMESTATE_InProgress = 2,
	ASSASSINMINIGAMESTATE_ContractFilled = 3,
	ASSASSINMINIGAMESTATE_ContractDenied = 4,
};

enum class InputLayoutVariation_t : unsigned long
{
	INPUT_LAYOUT_VARIATION_DEFAULT = 0,
	INPUT_LAYOUT_VARIATION_STREAM1_MAT3X4 = 1,
	INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID = 2,
	INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID_IRRADIANCEINFO = 3,
	INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID_MORPH_VERT_ID = 4,
	INPUT_LAYOUT_VARIATION_MAX = 5,
};

enum class IrradVolumeFlags_t : unsigned long
{
	IRRADVOLUME_FLAGS_NONE = 0,
	IRRADVOLUME_FLAG_AUTO_GENERATED = 1,
};

enum class ItemQuality_t : unsigned long
{
	DOTA_ITEM_QUALITY_CONSUMABLE = 0,
	DOTA_ITEM_QUALITY_PLAIN = 1,
	DOTA_ITEM_QUALITY_COMMON = 2,
	DOTA_ITEM_QUALITY_RARE = 3,
	DOTA_ITEM_QUALITY_EPIC = 4,
	DOTA_ITEM_QUALITY_ARTIFACT = 5,
	DOTA_ITEM_QUALITY_SECRET_SHOP = 6,
	NUM_ITEM_QUALITY_LEVELS = 7,
};

enum class LatchDirtyPermission_t : unsigned long
{
	LATCH_DIRTY_DISALLOW = 0,
	LATCH_DIRTY_SERVER_CONTROLLED = 1,
	LATCH_DIRTY_CLIENT_SIMULATED = 2,
	LATCH_DIRTY_PREDICTION = 3,
	LATCH_DIRTY_FRAMESIMULATE = 4,
	LATCH_DIRTY_PARTICLE_SIMULATE = 5,
};

enum class LayoutPositionType_e : unsigned long
{
	LAYOUTPOSITIONTYPE_VIEWPORT_RELATIVE = 0,
	LAYOUTPOSITIONTYPE_FRACTIONAL = 1,
	LAYOUTPOSITIONTYPE_NONE = 2,
};

enum class LifeState_t : unsigned long
{
	LIFE_ALIVE = 0,
	LIFE_DYING = 1,
	LIFE_DEAD = 2,
	LIFE_RESPAWNABLE = 3,
};

enum class LightSourceShape_t : unsigned long
{
	LIGHT_SOURCE_SHAPE_SPHERE = 0,
};

enum class LightType_t : unsigned long
{
	MATERIAL_LIGHT_DISABLE = 0,
	MATERIAL_LIGHT_POINT = 1,
	MATERIAL_LIGHT_DIRECTIONAL = 2,
	MATERIAL_LIGHT_SPOT = 3,
	MATERIAL_LIGHT_UNUSED = 4,
	MATERIAL_LIGHT_ENVIRONMENT_PROBE = 5,
};

enum class LocalFlexController_t : unsigned long
{
	DUMMY_FLEX_CONTROLLER = 2147483647,
};

enum class LuaModifierType : unsigned long
{
	LUA_MODIFIER_MOTION_NONE = 0,
	LUA_MODIFIER_MOTION_HORIZONTAL = 1,
	LUA_MODIFIER_MOTION_VERTICAL = 2,
	LUA_MODIFIER_MOTION_BOTH = 3,
	LUA_MODIFIER_INVALID = 4,
};

enum class MaterialModifyMode_t : unsigned long
{
	MATERIAL_MODIFY_MODE_NONE = 0,
	MATERIAL_MODIFY_MODE_SETVAR = 1,
	MATERIAL_MODIFY_MODE_ANIM_SEQUENCE = 2,
	MATERIAL_MODIFY_MODE_FLOAT_LERP = 3,
};

enum class Materials : unsigned long
{
	matGlass = 0,
	matWood = 1,
	matMetal = 2,
	matFlesh = 3,
	matCinderBlock = 4,
	matCeilingTile = 5,
	matComputer = 6,
	matUnbreakableGlass = 7,
	matRocks = 8,
	matWeb = 9,
	matNone = 10,
	matLastMaterial = 11,
};

enum class MeshDrawPrimitiveFlags_t : unsigned long
{
	MESH_DRAW_FLAGS_NONE = 0,
	MESH_DRAW_FLAGS_USE_SHADOW_FAST_PATH = 1,
	MESH_DRAW_FLAGS_USE_COMPRESSED_NORMAL_TANGENT = 2,
	MESH_DRAW_FLAGS_IS_OCCLUDER = 4,
	MESH_DRAW_INPUT_LAYOUT_IS_NOT_MATCHED_TO_MATERIAL = 8,
	MESH_DRAW_FLAGS_USE_COMPRESSED_PER_VERTEX_LIGHTING = 16,
	MESH_DRAW_FLAGS_USE_UNCOMPRESSED_PER_VERTEX_LIGHTING = 32,
};

enum class MeshTranslucencyType_t : unsigned long
{
	MESH_TRANSLUCENCY_FULLY_OPAQUE = 0,
	MESH_TRANSLUCENCY_PARTIALLY_ALPHA_BLENDED = 1,
	MESH_TRANSLUCENCY_FULLY_ALPHA_BLENDED = 2,
};

enum class ModelBoneFlexComponent_t : signed long
{
	MODEL_BONE_FLEX_INVALID = -1,
	MODEL_BONE_FLEX_TX = 0,
	MODEL_BONE_FLEX_TY = 1,
	MODEL_BONE_FLEX_TZ = 2,
};

enum class MoveCollide_t : unsigned char
{
	MOVECOLLIDE_DEFAULT = 0,
	MOVECOLLIDE_FLY_BOUNCE = 1,
	MOVECOLLIDE_FLY_CUSTOM = 2,
	MOVECOLLIDE_FLY_SLIDE = 3,
	MOVECOLLIDE_COUNT = 4,
	MOVECOLLIDE_MAX_BITS = 3,
};

enum class MoveType_t : unsigned char
{
	MOVETYPE_NONE = 0,
	MOVETYPE_ISOMETRIC = 1,
	MOVETYPE_WALK = 2,
	MOVETYPE_STEP = 3,
	MOVETYPE_FLY = 4,
	MOVETYPE_FLYGRAVITY = 5,
	MOVETYPE_VPHYSICS = 6,
	MOVETYPE_PUSH = 7,
	MOVETYPE_NOCLIP = 8,
	MOVETYPE_LADDER = 9,
	MOVETYPE_OBSERVER = 10,
	MOVETYPE_CUSTOM = 11,
	MOVETYPE_LAST = 11,
	MOVETYPE_MAX_BITS = 4,
};

enum class NavAttributeEnum : unsigned long long
{
	NAV_MESH_CROUCH = 1,
	NAV_MESH_JUMP = 2,
	NAV_MESH_PRECISE = 4,
	NAV_MESH_NO_JUMP = 8,
	NAV_MESH_AVOID = 128,
	NAV_MESH_STAIRS = 4096,
	NAV_MESH_NO_MERGE = 8192,
	NAV_MESH_OBSTACLE_TOP = 16384,
	NAV_MESH_CLIFF = 32768,
};

enum class NavDirType : unsigned long
{
	NORTH = 0,
	EAST = 1,
	SOUTH = 2,
	WEST = 3,
	NUM_DIRECTIONS = 4,
};

enum class NetChannelBufType_t : signed long
{
	BUF_DEFAULT = -1,
	BUF_UNRELIABLE = 0,
	BUF_RELIABLE = 1,
	BUF_VOICE = 2,
};

enum class ObjectTypeFlags_t : unsigned long
{
	OBJECT_TYPE_IMAGE_LOD = 1,
	OBJECT_TYPE_GEOMETRY_LOD = 2,
	OBJECT_TYPE_DECAL = 4,
	OBJECT_TYPE_MODEL = 8,
	OBJECT_TYPE_BLOCK_LIGHT = 16,
	OBJECT_TYPE_NO_SHADOWS = 32,
	OBJECT_TYPE_WORLDSPACE_TEXURE_BLEND = 64,
	OBJECT_TYPE_DISABLED_IN_LOW_QUALITY = 128,
};

enum class ObstructionRelationshipClass_t : unsigned long
{
	DOTA_OBSTRUCTION_RELATIONSHIP_NONE = 0,
	DOTA_OBSTRUCTION_RELATIONSHIP_BUILDING = 1,
	DOTA_OBSTRUCTION_RELATIONSHIP_PLAYER_CONTROLLED = 2,
	DOTA_OBSTRUCTION_RELATIONSHIP_NPC = 3,
	DOTA_OBSTRUCTION_RELATIONSHIP_LAST = 4,
};

enum class ParticleAttachment_t : signed long
{
	PATTACH_INVALID = -1,
	PATTACH_ABSORIGIN = 0,
	PATTACH_ABSORIGIN_FOLLOW = 1,
	PATTACH_CUSTOMORIGIN = 2,
	PATTACH_CUSTOMORIGIN_FOLLOW = 3,
	PATTACH_POINT = 4,
	PATTACH_POINT_FOLLOW = 5,
	PATTACH_EYES_FOLLOW = 6,
	PATTACH_OVERHEAD_FOLLOW = 7,
	PATTACH_WORLDORIGIN = 8,
	PATTACH_ROOTBONE_FOLLOW = 9,
	PATTACH_RENDERORIGIN_FOLLOW = 10,
	PATTACH_MAIN_VIEW = 11,
	PATTACH_WATERWAKE = 12,
	MAX_PATTACH_TYPES = 13,
};

enum class ParticleColorBlendMode_t : unsigned long
{
	PARTICLEBLEND_DEFAULT = 0,
	PARTICLEBLEND_OVERLAY = 1,
	PARTICLEBLEND_DARKEN = 2,
	PARTICLEBLEND_LIGHTEN = 3,
	PARTICLEBLEND_MULTIPLY = 4,
};

enum class ParticleOrientationChoiceList_t : unsigned long
{
	PARTICLE_ORIENTATION_SCREEN_ALIGNED = 0,
	PARTICLE_ORIENTATION_SCREEN_Z_ALIGNED = 1,
	PARTICLE_ORIENTATION_WORLD_Z_ALIGNED = 2,
	PARTICLE_ORIENTATION_ALIGN_TO_PARTICLE_NORMAL = 3,
	PARTICLE_ORIENTATION_SCREENALIGN_TO_PARTICLE_NORMAL = 4,
};

enum class PerformanceMode_t : unsigned long
{
	PM_NORMAL = 0,
	PM_NO_GIBS = 1,
	PM_FULL_GIBS = 2,
	PM_REDUCED_GIBS = 3,
};

enum class PetCoopStates_t : unsigned long
{
	COOP_IGNORE = 0,
	COOPTELEPORT_START_PERFORMING = 1,
	COOPTELEPORT_PLAY_ENDANIM = 2,
	COOPTELEPORT_PLAY_EXITANIM = 3,
	COOP_WARD_OBSERVER = 4,
	COOP_WARD_SENTRY = 5,
};

enum class PhysicsSolverProfile_t : unsigned long
{
	PHYSICS_SOLVER_PROFILE_DEFAULT = 0,
	PHYSICS_SOLVER_PROFILE_STABILIZED = 1,
	PHYSICS_SOLVER_PROFILE_CRITICAL = 2,
};

enum class PlayerConnectedState : unsigned long
{
	PlayerConnected = 0,
	PlayerDisconnecting = 1,
	PlayerDisconnected = 2,
};

enum class PlayerOrderIssuer_t : unsigned long
{
	DOTA_ORDER_ISSUER_SELECTED_UNITS = 0,
	DOTA_ORDER_ISSUER_CURRENT_UNIT_ONLY = 1,
	DOTA_ORDER_ISSUER_HERO_ONLY = 2,
	DOTA_ORDER_ISSUER_PASSED_UNIT_ONLY = 3,
};

enum class PlayerUltimateStateOrTime_t : signed long
{
	PLAYER_ULTIMATE_STATE_READY = 0,
	PLAYER_ULTIMATE_STATE_NO_MANA = -1,
	PLAYER_ULTIMATE_STATE_NOT_LEVELED = -2,
	PLAYER_ULTIMATE_STATE_HIDDEN = -3,
};

enum class PointTemplateClientOnlyEntityBehavior_t : unsigned long
{
	CREATE_FOR_CURRENTLY_CONNECTED_CLIENTS_ONLY = 0,
	CREATE_FOR_CLIENTS_WHO_CONNECT_LATER = 1,
};

enum class PointTemplateOwnerSpawnGroupType_t : unsigned long
{
	INSERT_INTO_POINT_TEMPLATE_SPAWN_GROUP = 0,
	INSERT_INTO_CURRENTLY_ACTIVE_SPAWN_GROUP = 1,
	INSERT_INTO_NEWLY_CREATED_SPAWN_GROUP = 2,
};

enum class PointWorldTextJustifyHorizontal_t : unsigned long
{
	POINT_WORLD_TEXT_JUSTIFY_HORIZONTAL_LEFT = 0,
	POINT_WORLD_TEXT_JUSTIFY_HORIZONTAL_CENTER = 1,
	POINT_WORLD_TEXT_JUSTIFY_HORIZONTAL_RIGHT = 2,
};

enum class PointWorldTextJustifyVertical_t : unsigned long
{
	POINT_WORLD_TEXT_JUSTIFY_VERTICAL_BOTTOM = 0,
	POINT_WORLD_TEXT_JUSTIFY_VERTICAL_CENTER = 1,
	POINT_WORLD_TEXT_JUSTIFY_VERTICAL_TOP = 2,
};

enum class PointWorldTextReorientMode_t : unsigned long
{
	POINT_WORLD_TEXT_REORIENT_NONE = 0,
	POINT_WORLD_TEXT_REORIENT_AROUND_UP = 1,
};

enum class PoseController_FModType_t : unsigned long
{
	POSECONTROLLER_FMODTYPE_NONE = 0,
	POSECONTROLLER_FMODTYPE_SINE = 1,
	POSECONTROLLER_FMODTYPE_SQUARE = 2,
	POSECONTROLLER_FMODTYPE_TRIANGLE = 3,
	POSECONTROLLER_FMODTYPE_SAWTOOTH = 4,
	POSECONTROLLER_FMODTYPE_NOISE = 5,
	POSECONTROLLER_FMODTYPE_TOTAL = 6,
};

enum class PostProcessParameterNames_t : unsigned long
{
	PPPN_FADE_TIME = 0,
	PPPN_LOCAL_CONTRAST_STRENGTH = 1,
	PPPN_LOCAL_CONTRAST_EDGE_STRENGTH = 2,
	PPPN_VIGNETTE_START = 3,
	PPPN_VIGNETTE_END = 4,
	PPPN_VIGNETTE_BLUR_STRENGTH = 5,
	PPPN_FADE_TO_BLACK_STRENGTH = 6,
	PPPN_DEPTH_BLUR_FOCAL_DISTANCE = 7,
	PPPN_DEPTH_BLUR_STRENGTH = 8,
	PPPN_SCREEN_BLUR_STRENGTH = 9,
	PPPN_FILM_GRAIN_STRENGTH = 10,
	PPPN_TOP_VIGNETTE_STRENGTH = 11,
	POST_PROCESS_PARAMETER_COUNT = 12,
};

enum class PrecipitationType_t : unsigned long
{
	PRECIPITATION_TYPE_RAIN = 0,
	PRECIPITATION_TYPE_SNOW = 1,
	PRECIPITATION_TYPE_ASH = 2,
	PRECIPITATION_TYPE_SNOWFALL = 3,
	PRECIPITATION_TYPE_PARTICLERAIN = 4,
	PRECIPITATION_TYPE_PARTICLEASH = 5,
	PRECIPITATION_TYPE_PARTICLERAINSTORM = 6,
	PRECIPITATION_TYPE_PARTICLEBUGS = 7,
	PRECIPITATION_TYPE_PARTICLESMOKE = 8,
	PRECIPITATION_TYPE_PARTICLESNOW = 9,
	NUM_PRECIPITATION_TYPES = 10,
};

enum class PropDoorRotatingOpenDirection_e : unsigned long
{
	DOOR_ROTATING_OPEN_BOTH_WAYS = 0,
	DOOR_ROTATING_OPEN_FORWARD = 1,
	DOOR_ROTATING_OPEN_BACKWARD = 2,
};

enum class PropDoorRotatingSpawnPos_t : unsigned long
{
	DOOR_SPAWN_CLOSED = 0,
	DOOR_SPAWN_OPEN_FORWARD = 1,
	DOOR_SPAWN_OPEN_BACK = 2,
	DOOR_SPAWN_AJAR = 3,
};

enum class RMSG_EventType_t : signed long
{
	RMSG_EVENT_INVALID = -1,
	RMSG_SYSTEM_FRAME_BOUNDARY = 0,
	RMSG_SYSTEM_BLOCKING_LOAD = 1,
	RMSG_SYSTEM_TYPE_MANAGER_UPDATE = 2,
	RMSG_RESOURCE_LOAD_REQUEST_QUEUED = 3,
	RMSG_RESOURCE_HEADER_IO = 4,
	RMSG_RESOURCE_HEADER_LOADED = 5,
	RMSG_RESOURCE_DATA_IO = 6,
	RMSG_RESOURCE_DATA_LOADED = 7,
	RMSG_RESOURCE_AUTOCONVERT = 8,
	RMSG_RESOURCE_EXTREF_FIXUP = 9,
	RMSG_RESOURCE_ALLOCATE = 10,
	RMSG_CLEANUP_REFERENCES = 11,
	RMSG_RESOURCE_DEALLOCATE = 12,
	RMSG_RESOURCE_LOAD_COMPLETED = 13,
	RMSG_RESOURCE_LOAD_FAILED = 14,
	RMSG_RESOURCE_LOAD_NAMEONLY_COMPLETED = 15,
	RMSG_MANIFEST_DATA_LOADED = 16,
	RMSG_MANIFEST_BLOCKING_LOAD = 17,
	RMSG_MANIFEST_LOAD_COMPLETED = 18,
	RMSG_ENTITY_SPAWN = 19,
	RMSG_ENTITY_ACTIVATE = 20,
	RMSG_ENTITY_DELETE = 21,
	RMSG_ENTITY_COMPONENTS_ACTIVATE = 22,
	RMSG_PRE_SPAWN_GROUP_LOAD = 23,
	RMSG_POST_SPAWN_GROUP_LOAD = 24,
	RMSG_UNUSED_1 = 25,
	RMSG_UNUSED_2 = 26,
	RMSG_UNUSED_3 = 27,
	RMSG_UNUSED_4 = 28,
	RMSG_UNUSED_5 = 29,
	RMSG_UNUSED_6 = 30,
	RMSG_UNUSED_7 = 31,
	RMSG_UNUSED_8 = 32,
	RMSG_EVENT_COUNT = 33,
};

enum class RMSG_SubEventType_t : signed long
{
	RMSG_SUB_EVENT_INVALID = -1,
	RMSG_SUB_EVENT_INSTANT = 0,
	RMSG_SUB_EVENT_BEGIN_SPAN = 1,
	RMSG_SUB_EVENT_END_SPAN = 2,
	RMSG_SUB_EVENT_COUNT = 3,
};

enum class RenderFx_t : unsigned char
{
	kRenderFxNone = 0,
	kRenderFxPulseSlow = 1,
	kRenderFxPulseFast = 2,
	kRenderFxPulseSlowWide = 3,
	kRenderFxPulseFastWide = 4,
	kRenderFxFadeSlow = 5,
	kRenderFxFadeFast = 6,
	kRenderFxSolidSlow = 7,
	kRenderFxSolidFast = 8,
	kRenderFxStrobeSlow = 9,
	kRenderFxStrobeFast = 10,
	kRenderFxStrobeFaster = 11,
	kRenderFxFlickerSlow = 12,
	kRenderFxFlickerFast = 13,
	kRenderFxNoDissipation = 14,
	kRenderFxFadeOut = 15,
	kRenderFxFadeIn = 16,
	kRenderFxPulseFastWider = 17,
	kRenderFxGlowShell = 18,
	kRenderFxMax = 19,
};

enum class RenderMeshFlexControllerRemapType_t : unsigned long
{
	FLEXCONTROLLER_REMAP_PASSTHRU = 0,
	FLEXCONTROLLER_REMAP_2WAY = 1,
	FLEXCONTROLLER_REMAP_NWAY = 2,
	FLEXCONTROLLER_REMAP_EYELID = 3,
};

enum class RenderMode_t : unsigned char
{
	kRenderNormal = 0,
	kRenderTransColor = 1,
	kRenderTransTexture = 2,
	kRenderGlow = 3,
	kRenderTransAlpha = 4,
	kRenderTransAdd = 5,
	kRenderEnvironmental = 6,
	kRenderTransAddFrameBlend = 7,
	kRenderTransAlphaAdd = 8,
	kRenderWorldGlow = 9,
	kRenderNone = 10,
	kRenderDevVisualizer = 11,
	kRenderModeCount = 12,
};

enum class RenderMultisampleType_t : signed long
{
	RENDER_MULTISAMPLE_INVALID = -1,
	RENDER_MULTISAMPLE_NONE = 0,
	RENDER_MULTISAMPLE_2X = 1,
	RENDER_MULTISAMPLE_4X = 2,
	RENDER_MULTISAMPLE_6X = 3,
	RENDER_MULTISAMPLE_8X = 4,
	RENDER_MULTISAMPLE_16X = 5,
	RENDER_MULTISAMPLE_TYPE_COUNT = 6,
};

enum class RenderPrimitiveType_t : unsigned long
{
	RENDER_PRIM_POINTS = 0,
	RENDER_PRIM_LINES = 1,
	RENDER_PRIM_LINES_WITH_ADJACENCY = 2,
	RENDER_PRIM_LINE_STRIP = 3,
	RENDER_PRIM_LINE_STRIP_WITH_ADJACENCY = 4,
	RENDER_PRIM_TRIANGLES = 5,
	RENDER_PRIM_TRIANGLES_WITH_ADJACENCY = 6,
	RENDER_PRIM_TRIANGLE_STRIP = 7,
	RENDER_PRIM_TRIANGLE_STRIP_WITH_ADJACENCY = 8,
	RENDER_PRIM_INSTANCED_QUADS = 9,
	RENDER_PRIM_HETEROGENOUS = 10,
	RENDER_PRIM_1_CONTROL_POINT_PATCHLIST = 11,
	RENDER_PRIM_2_CONTROL_POINT_PATCHLIST = 12,
	RENDER_PRIM_3_CONTROL_POINT_PATCHLIST = 13,
	RENDER_PRIM_4_CONTROL_POINT_PATCHLIST = 14,
	RENDER_PRIM_5_CONTROL_POINT_PATCHLIST = 15,
	RENDER_PRIM_6_CONTROL_POINT_PATCHLIST = 16,
	RENDER_PRIM_7_CONTROL_POINT_PATCHLIST = 17,
	RENDER_PRIM_8_CONTROL_POINT_PATCHLIST = 18,
	RENDER_PRIM_9_CONTROL_POINT_PATCHLIST = 19,
	RENDER_PRIM_10_CONTROL_POINT_PATCHLIST = 20,
	RENDER_PRIM_11_CONTROL_POINT_PATCHLIST = 21,
	RENDER_PRIM_12_CONTROL_POINT_PATCHLIST = 22,
	RENDER_PRIM_13_CONTROL_POINT_PATCHLIST = 23,
	RENDER_PRIM_14_CONTROL_POINT_PATCHLIST = 24,
	RENDER_PRIM_15_CONTROL_POINT_PATCHLIST = 25,
	RENDER_PRIM_16_CONTROL_POINT_PATCHLIST = 26,
	RENDER_PRIM_17_CONTROL_POINT_PATCHLIST = 27,
	RENDER_PRIM_18_CONTROL_POINT_PATCHLIST = 28,
	RENDER_PRIM_19_CONTROL_POINT_PATCHLIST = 29,
	RENDER_PRIM_20_CONTROL_POINT_PATCHLIST = 30,
	RENDER_PRIM_21_CONTROL_POINT_PATCHLIST = 31,
	RENDER_PRIM_22_CONTROL_POINT_PATCHLIST = 32,
	RENDER_PRIM_23_CONTROL_POINT_PATCHLIST = 33,
	RENDER_PRIM_24_CONTROL_POINT_PATCHLIST = 34,
	RENDER_PRIM_25_CONTROL_POINT_PATCHLIST = 35,
	RENDER_PRIM_26_CONTROL_POINT_PATCHLIST = 36,
	RENDER_PRIM_27_CONTROL_POINT_PATCHLIST = 37,
	RENDER_PRIM_28_CONTROL_POINT_PATCHLIST = 38,
	RENDER_PRIM_29_CONTROL_POINT_PATCHLIST = 39,
	RENDER_PRIM_30_CONTROL_POINT_PATCHLIST = 40,
	RENDER_PRIM_31_CONTROL_POINT_PATCHLIST = 41,
	RENDER_PRIM_32_CONTROL_POINT_PATCHLIST = 42,
	RENDER_PRIM_TYPE_COUNT = 43,
};

enum class RenderSlotType_t : signed long
{
	RENDER_SLOT_INVALID = -1,
	RENDER_SLOT_PER_VERTEX = 0,
	RENDER_SLOT_PER_INSTANCE = 1,
};

enum class ResourceDependencyFlags_t : unsigned long
{
	RESOURCE_INPUT_DEPENDENCY_OPTIONAL = 1,
	RESOURCE_INPUT_DEPENDENCY_EXISTS = 2,
};

enum class ResourceIntrospectionVersion_t : unsigned long
{
	RESOURCE_INTROSPECTION_VERSION = 4,
};

enum class ResourceStructFlags_t : unsigned long
{
	STRUCT_HAS_VTABLE = 1,
	STRUCT_TREE_REQUIRES_SCATTER = 2,
	STRUCT_TREE_REQUIRES_CONSTRUCTOR = 4,
	STRUCT_TREE_REQUIRES_DESTRUCTOR = 8,
	STRUCT_TREE_REQUIRES_EXT_REFERENCES = 16,
	STRUCT_TREE_REQUIRES_DEF_REFERENCES = 32,
	STRUCT_FLAGS_MAX = 32,
};

enum class SPELL_IMMUNITY_TYPES : unsigned long
{
	SPELL_IMMUNITY_NONE = 0,
	SPELL_IMMUNITY_ALLIES_YES = 1,
	SPELL_IMMUNITY_ALLIES_NO = 2,
	SPELL_IMMUNITY_ENEMIES_YES = 3,
	SPELL_IMMUNITY_ENEMIES_NO = 4,
};

enum class SchemaClassFlags_t : unsigned long
{
	SCHEMA_CLASS_HAS_VIRTUAL_MEMBERS = 1,
	SCHEMA_CLASS_IS_ABSTRACT = 2,
	SCHEMA_CLASS_HAS_TRIVIAL_CONSTRUCTOR = 4,
	SCHEMA_CLASS_HAS_TRIVIAL_DESTRUCTOR = 8,
	SCHEMA_CLASS_TEMP_HACK_HAS_NOSCHEMA_MEMBERS = 16,
	SCHEMA_CLASS_TEMP_HACK_HAS_CONSTRUCTOR_LIKE_METHODS = 32,
	SCHEMA_CLASS_TEMP_HACK_HAS_DESTRUCTOR_LIKE_METHODS = 64,
	SCHEMA_CLASS_IS_NOSCHEMA_CLASS = 128,
};

enum class SchemaFieldType_t : unsigned long
{
	SCHEMA_FIELD_TYPE_UNKNOWN = 0,
	SCHEMA_FIELD_TYPE_STRUCT = 1,
	SCHEMA_FIELD_TYPE_ENUM = 2,
	SCHEMA_FIELD_TYPE_EXT_REFERENCE = 3,
	SCHEMA_FIELD_TYPE_CHAR = 4,
	SCHEMA_FIELD_TYPE_UCHAR = 5,
	SCHEMA_FIELD_TYPE_INT = 6,
	SCHEMA_FIELD_TYPE_UINT = 7,
	SCHEMA_FIELD_TYPE_FLOAT = 8,
	SCHEMA_FIELD_TYPE_DOUBLE = 9,
	SCHEMA_FIELD_TYPE_INT8 = 10,
	SCHEMA_FIELD_TYPE_UINT8 = 11,
	SCHEMA_FIELD_TYPE_INT16 = 12,
	SCHEMA_FIELD_TYPE_UINT16 = 13,
	SCHEMA_FIELD_TYPE_INT32 = 14,
	SCHEMA_FIELD_TYPE_UINT32 = 15,
	SCHEMA_FIELD_TYPE_INT64 = 16,
	SCHEMA_FIELD_TYPE_UINT64 = 17,
	SCHEMA_FIELD_TYPE_FLOAT32 = 18,
	SCHEMA_FIELD_TYPE_FLOAT64 = 19,
	SCHEMA_FIELD_TYPE_TIME = 20,
	SCHEMA_FIELD_TYPE_VECTOR2D = 21,
	SCHEMA_FIELD_TYPE_VECTOR3D = 22,
	SCHEMA_FIELD_TYPE_VECTOR4D = 23,
	SCHEMA_FIELD_TYPE_QANGLE = 24,
	SCHEMA_FIELD_TYPE_QUATERNION = 25,
	SCHEMA_FIELD_TYPE_VMATRIX = 26,
	SCHEMA_FIELD_TYPE_FLTX4 = 27,
	SCHEMA_FIELD_TYPE_COLOR = 28,
	SCHEMA_FIELD_TYPE_UNIQUEID = 29,
	SCHEMA_FIELD_TYPE_BOOL = 30,
	SCHEMA_FIELD_TYPE_RESOURCE_STRING = 31,
	SCHEMA_FIELD_TYPE_VOID = 32,
	SCHEMA_FIELD_TYPE_MATRIX3X4 = 33,
	SCHEMA_FIELD_TYPE_UTLSYMBOL = 34,
	SCHEMA_FIELD_TYPE_UTLSTRING = 35,
	SCHEMA_FIELD_TYPE_MATRIX3X4A = 36,
	SCHEMA_FIELD_TYPE_UTLBINARYBLOCK = 37,
	SCHEMA_FIELD_TYPE_UUID = 38,
	SCHEMA_FIELD_TYPE_OPAQUE_TYPE = 39,
	SCHEMA_FIELD_TYPE_TRANSFORM = 40,
	SCHEMA_FIELD_TYPE_DEF_REFERENCE = 41,
	SCHEMA_FIELD_TYPE_RADIANEULER = 42,
	SCHEMA_FIELD_TYPE_DEGREEEULER = 43,
	SCHEMA_FIELD_TYPE_FOURVECTORS = 44,
	SCHEMA_FIELD_TYPE_COUNT = 45,
};

enum class ScreenEffectType_t : unsigned long
{
	SCREENEFFECT_EP2_ADVISOR_STUN = 0,
	SCREENEFFECT_EP1_INTRO = 1,
	SCREENEFFECT_EP2_GROGGY = 2,
};

enum class SeqResourceCmdEnum : unsigned long
{
	SEQ_CMD_Nop = 0,
	SEQ_CMD_LinearDelta = 1,
	SEQ_CMD_FetchFrameRange = 2,
	SEQ_CMD_Slerp = 3,
	SEQ_CMD_Add = 4,
	SEQ_CMD_Subtract = 5,
	SEQ_CMD_Scale = 6,
	SEQ_CMD_Copy = 7,
	SEQ_CMD_Blend = 8,
	SEQ_CMD_Worldspace = 9,
	SEQ_CMD_Sequence = 10,
	SEQ_CMD_FetchCycle = 11,
	SEQ_CMD_FetchFrame = 12,
	SEQ_CMD_IKLockInPlace = 13,
	SEQ_CMD_IKRestoreAll = 14,
	SEQ_CMD_ReverseSequence = 15,
};

enum class SeqResourcePoseSettingEnum : unsigned long
{
	SEQ_POSE_CONSTANT = 0,
	SEQ_POSE_ROTATION = 1,
	SEQ_POSE_POSITION = 2,
	SEQ_POSE_VELOCITY = 3,
};

enum class SequenceCombineMode_t : unsigned long
{
	SEQUENCE_COMBINE_MODE_USE_SEQUENCE_0 = 0,
	SEQUENCE_COMBINE_MODE_USE_SEQUENCE_1 = 1,
	SEQUENCE_COMBINE_MODE_AVERAGE = 2,
	SEQUENCE_COMBINE_MODE_ADDITIVE = 3,
	SEQUENCE_COMBINE_MODE_ALPHA_FROM0_RGB_FROM_1 = 4,
	SEQUENCE_COMBINE_MODE_ALPHA_FROM1_RGB_FROM_0 = 5,
	SEQUENCE_COMBINE_MODE_WEIGHTED_BLEND = 6,
	SEQUENCE_COMBINE_MODE_ALPHA_BLEND_1_OVER_0 = 7,
	SEQUENCE_COMBINE_MODE_REPLICATEALPHA0 = 8,
	SEQUENCE_COMBINE_MODE_REPLICATEALPHA1 = 9,
	SEQUENCE_COMBINE_MODE_ALPHA_BLEND_0_OVER_1 = 10,
	SEQUENCE_COMBINE_MODE_REPLICATE_COLOR_0 = 11,
	SEQUENCE_COMBINE_MODE_REPLICATE_COLOR_1 = 12,
};

enum class ShadowType_t : unsigned long
{
	SHADOWS_NONE = 0,
	SHADOWS_SIMPLE = 1,
};

enum class ShakeCommand_t : unsigned long
{
	SHAKE_START = 0,
	SHAKE_STOP = 1,
	SHAKE_AMPLITUDE = 2,
	SHAKE_FREQUENCY = 3,
	SHAKE_START_RUMBLEONLY = 4,
	SHAKE_START_NORUMBLE = 5,
};

enum class ShatterSurface_t : unsigned long
{
	SHATTERSURFACE_GLASS = 0,
	SHATTERSURFACE_TILE = 1,
};

enum class ShopItemViewMode_t : unsigned long
{
	SHOP_VIEW_MODE_LIST = 0,
	SHOP_VIEW_MODE_GRID = 1,
};

enum class SignonState_t : unsigned long
{
	SIGNONSTATE_NONE = 0,
	SIGNONSTATE_CHALLENGE = 1,
	SIGNONSTATE_CONNECTED = 2,
	SIGNONSTATE_NEW = 3,
	SIGNONSTATE_PRESPAWN = 4,
	SIGNONSTATE_SPAWN = 5,
	SIGNONSTATE_FULL = 6,
	SIGNONSTATE_CHANGELEVEL = 7,
};

enum class SolidType_t : unsigned char
{
	SOLID_NONE = 0,
	SOLID_BSP = 1,
	SOLID_BBOX = 2,
	SOLID_OBB = 3,
	SOLID_POINT = 5,
	SOLID_VPHYSICS = 6,
	SOLID_CAPSULE = 7,
	SOLID_LAST = 8,
};

enum class SosEditItemType_t : unsigned long
{
	SOS_EDIT_ITEM_TYPE_SOUNDEVENTS = 0,
	SOS_EDIT_ITEM_TYPE_SOUNDEVENT = 1,
	SOS_EDIT_ITEM_TYPE_LIBRARYSTACKS = 2,
	SOS_EDIT_ITEM_TYPE_STACK = 3,
	SOS_EDIT_ITEM_TYPE_OPERATOR = 4,
	SOS_EDIT_ITEM_TYPE_FIELD = 5,
};

enum class SpeechPriorityType : unsigned long
{
	SPEECH_PRIORITY_LOW = 0,
	SPEECH_PRIORITY_NORMAL = 1,
	SPEECH_PRIORITY_MANUAL = 2,
	SPEECH_PRIORITY_UNINTERRUPTABLE = 3,
};

enum class StartupBehavior_t : unsigned long
{
	HERO_STARTUP_BEHAVIOR_DEFAULT = 0,
	HERO_STARTUP_BEHAVIOR_TAUNT = 1,
	HERO_STARTUP_BEHAVIOR_VOICE = 2,
};

enum class SurroundingBoundsType_t : unsigned char
{
	USE_OBB_COLLISION_BOUNDS = 0,
	USE_BEST_COLLISION_BOUNDS = 1,
	USE_HITBOXES = 2,
	USE_SPECIFIED_BOUNDS = 3,
	USE_GAME_CODE = 4,
	USE_ROTATION_EXPANDED_BOUNDS = 5,
	USE_COLLISION_BOUNDS_NEVER_VPHYSICS = 6,
	USE_ROTATION_EXPANDED_SEQUENCE_BOUNDS = 7,
	SURROUNDING_TYPE_BIT_COUNT = 3,
};

enum class TOGGLE_STATE : unsigned long
{
	TS_AT_TOP = 0,
	TS_AT_BOTTOM = 1,
	TS_GOING_UP = 2,
	TS_GOING_DOWN = 3,
	DOOR_OPEN = 0,
	DOOR_CLOSED = 1,
	DOOR_OPENING = 2,
	DOOR_CLOSING = 3,
};

enum class TRAIN_CODE : unsigned long
{
	TRAIN_SAFE = 0,
	TRAIN_BLOCKING = 1,
	TRAIN_FOLLOWING = 2,
};

enum class TakeHealthOptions_t : unsigned long
{
	TH_IGNORE_MAX_HITPOINTS = 1,
};

enum class TextureSpecificationFlags_t : unsigned long
{
	TSPEC_FLAGS = 0,
	TSPEC_RENDER_TARGET = 1,
	TSPEC_VERTEX_TEXTURE = 2,
	TSPEC_UNFILTERABLE_OK = 4,
	TSPEC_RENDER_TARGET_SAMPLEABLE = 8,
	TSPEC_SUGGEST_CLAMPS = 16,
	TSPEC_SUGGEST_CLAMPT = 32,
	TSPEC_SUGGEST_CLAMPU = 64,
	TSPEC_NO_LOD = 128,
	TSPEC_CUBE_TEXTURE = 256,
	TSPEC_VOLUME_TEXTURE = 512,
	TSPEC_TEXTURE_ARRAY = 1024,
	TSPEC_TEXTURE_GEN_MIP_MAPS = 2048,
	TSPEC_LINE_TEXTURE_360 = 4096,
	TSPEC_LINEAR_ADDRESSING_360 = 8192,
	TSPEC_USE_TYPED_IMAGEFORMAT = 16384,
	TSPEC_SHARED_RESOURCE = 32768,
};

enum class ThreeState_t : unsigned long
{
	TRS_FALSE = 0,
	TRS_TRUE = 1,
	TRS_NONE = 2,
};

enum class Touch_t : unsigned long
{
	touch_none = 0,
	touch_player_only = 1,
	touch_npc_only = 2,
	touch_player_or_npc = 3,
	touch_player_or_npc_or_physicsprop = 4,
};

enum class TrackOrientationType_t : unsigned long
{
	TrackOrientation_Fixed = 0,
	TrackOrientation_FacePath = 1,
	TrackOrientation_FacePathAngles = 2,
};

enum class TrainOrientationType_t : unsigned long
{
	TrainOrientation_Fixed = 0,
	TrainOrientation_AtPathTracks = 1,
	TrainOrientation_LinearBlend = 2,
	TrainOrientation_EaseInEaseOut = 3,
};

enum class TrainVelocityType_t : unsigned long
{
	TrainVelocity_Instantaneous = 0,
	TrainVelocity_LinearBlend = 1,
	TrainVelocity_EaseInEaseOut = 2,
};

enum class UnitFilterResult : unsigned long
{
	UF_SUCCESS = 0,
	UF_FAIL_FRIENDLY = 1,
	UF_FAIL_ENEMY = 2,
	UF_FAIL_HERO = 3,
	UF_FAIL_CONSIDERED_HERO = 4,
	UF_FAIL_CREEP = 5,
	UF_FAIL_BUILDING = 6,
	UF_FAIL_MECHANICAL = 7,
	UF_FAIL_COURIER = 8,
	UF_FAIL_OTHER = 9,
	UF_FAIL_ANCIENT = 10,
	UF_FAIL_ILLUSION = 11,
	UF_FAIL_SUMMONED = 12,
	UF_FAIL_DOMINATED = 13,
	UF_FAIL_MELEE = 14,
	UF_FAIL_RANGED = 15,
	UF_FAIL_DEAD = 16,
	UF_FAIL_MAGIC_IMMUNE_ALLY = 17,
	UF_FAIL_MAGIC_IMMUNE_ENEMY = 18,
	UF_FAIL_INVULNERABLE = 19,
	UF_FAIL_IN_FOW = 20,
	UF_FAIL_INVISIBLE = 21,
	UF_FAIL_NOT_PLAYER_CONTROLLED = 22,
	UF_FAIL_ATTACK_IMMUNE = 23,
	UF_FAIL_CUSTOM = 24,
	UF_FAIL_INVALID_LOCATION = 25,
	UF_FAIL_DISABLE_HELP = 26,
	UF_FAIL_OUT_OF_WORLD = 27,
	UF_FAIL_NIGHTMARED = 28,
};

enum class ValueRemapperHapticsType_t : unsigned long
{
	HaticsType_Default = 0,
	HaticsType_None = 1,
};

enum class ValueRemapperInputType_t : unsigned long
{
	InputType_PlayerShootPosition = 0,
	InputType_PlayerShootPositionAroundAxis = 1,
};

enum class ValueRemapperMomentumType_t : unsigned long
{
	MomentumType_None = 0,
	MomentumType_Friction = 1,
	MomentumType_SpringTowardSnapValue = 2,
	MomentumType_SpringAwayFromSnapValue = 3,
};

enum class ValueRemapperOutputType_t : unsigned long
{
	OutputType_AnimationCycle = 0,
	OutputType_RotationX = 1,
	OutputType_RotationY = 2,
	OutputType_RotationZ = 3,
};

enum class ValueRemapperRatchetType_t : unsigned long
{
	RatchetType_Absolute = 0,
	RatchetType_EachEngage = 1,
};

enum class VertJustification_e : unsigned long
{
	VERT_JUSTIFICATION_TOP = 0,
	VERT_JUSTIFICATION_CENTER = 1,
	VERT_JUSTIFICATION_BOTTOM = 2,
	VERT_JUSTIFICATION_NONE = 3,
};

enum class WeaponProficiency_t : unsigned long
{
	WEAPON_PROFICIENCY_POOR = 0,
	WEAPON_PROFICIENCY_AVERAGE = 1,
	WEAPON_PROFICIENCY_GOOD = 2,
	WEAPON_PROFICIENCY_VERY_GOOD = 3,
	WEAPON_PROFICIENCY_PERFECT = 4,
};

enum class WeaponSound_t : unsigned long
{
	EMPTY = 0,
	SINGLE = 1,
	SINGLE_NPC = 2,
	WPN_DOUBLE = 3,
	DOUBLE_NPC = 4,
	BURST = 5,
	RELOAD = 6,
	RELOAD_NPC = 7,
	MELEE_MISS = 8,
	MELEE_HIT = 9,
	MELEE_HIT_WORLD = 10,
	SPECIAL1 = 11,
	SPECIAL2 = 12,
	SPECIAL3 = 13,
	TAUNT = 14,
	FAST_RELOAD = 15,
	NUM_SHOOT_SOUND_TYPES = 16,
};

enum class WeaponState_t : unsigned long
{
	WEAPON_NOT_CARRIED = 0,
	WEAPON_IS_CARRIED_BY_PLAYER = 1,
	WEAPON_IS_ACTIVE = 2,
};

enum class WeaponTexture_t : unsigned long
{
	WEAPON_TEXTURE_ICON_ACTIVE = 0,
	WEAPON_TEXTURE_ICON_INACTIVE = 1,
	WEAPON_TEXTURE_ICON_AMMO = 2,
	WEAPON_TEXTURE_ICON_AMMO2 = 3,
	WEAPON_TEXTURE_ICON_CROSSHAIR = 4,
	WEAPON_TEXTURE_ICON_AUTOAIM = 5,
	WEAPON_TEXTURE_ICON_ZOOMED_CROSSHAIR = 6,
	WEAPON_TEXTURE_ICON_ZOOMED_AUTOAIM = 7,
	WEAPON_TEXTURE_ICON_SMALL = 8,
};

enum class attributeprovidertypes_t : unsigned long
{
	PROVIDER_GENERIC = 0,
	PROVIDER_WEAPON = 1,
};

enum class doorCheck_e : unsigned long
{
	DOOR_CHECK_FORWARD = 0,
	DOOR_CHECK_BACKWARD = 1,
	DOOR_CHECK_FULL = 2,
};

enum class eEconItemOrigin : signed long
{
	kEconItemOrigin_Invalid = -1,
	kEconItemOrigin_Drop = 0,
	kEconItemOrigin_Achievement = 1,
	kEconItemOrigin_Purchased = 2,
	kEconItemOrigin_Traded = 3,
	kEconItemOrigin_Crafted = 4,
	kEconItemOrigin_StorePromotion = 5,
	kEconItemOrigin_Gifted = 6,
	kEconItemOrigin_SupportGranted = 7,
	kEconItemOrigin_FoundInCrate = 8,
	kEconItemOrigin_Earned = 9,
	kEconItemOrigin_ThirdPartyPromotion = 10,
	kEconItemOrigin_GiftWrapped = 11,
	kEconItemOrigin_HalloweenDrop = 12,
	kEconItemOrigin_PackageItem = 13,
	kEconItemOrigin_Foreign = 14,
	kEconItemOrigin_CDKey = 15,
	kEconItemOrigin_CollectionReward = 16,
	kEconItemOrigin_PreviewItem = 17,
	kEconItemOrigin_SteamWorkshopContribution = 18,
	kEconItemOrigin_PeriodicScoreReward = 19,
	kEconItemOrigin_Recycling = 20,
	kEconItemOrigin_TournamentDrop = 21,
	kEconItemOrigin_PassportReward = 22,
	kEconItemOrigin_TutorialDrop = 23,
	kEconItemOrigin_RecipeOutput = 24,
	kEconItemOrigin_GemExtract = 25,
	kEconItemOrigin_EventPointReward = 26,
	kEconItemOrigin_ItemRedemption = 27,
	kEconItemOrigin_FantasyTicketRefund = 28,
	kEconItemOrigin_VictoryPredictionReward = 29,
	kEconItemOrigin_AssassinEventReward = 30,
	kEconItemOrigin_CompendiumReward = 31,
	kEconItemOrigin_CompendiumDrop = 32,
	kEconItemOrigin_Max = 33,
};

enum class explosion_t : unsigned long
{
	EXPLOSION_DEFAULT = 0,
	EXPLOSION_GRENADE = 1,
	EXPLOSION_MOLOTOV = 2,
	EXPLOSION_FIREWORKS = 3,
};

enum class fieldtype_t : unsigned long
{
	FIELD_VOID = 0,
	FIELD_FLOAT = 1,
	FIELD_STRING = 2,
	FIELD_VECTOR = 3,
	FIELD_QUATERNION = 4,
	FIELD_INTEGER = 5,
	FIELD_BOOLEAN = 6,
	FIELD_SHORT = 7,
	FIELD_CHARACTER = 8,
	FIELD_COLOR32 = 9,
	FIELD_EMBEDDED = 10,
	FIELD_CUSTOM = 11,
	FIELD_CLASSPTR = 12,
	FIELD_EHANDLE = 13,
	FIELD_POSITION_VECTOR = 14,
	FIELD_TIME = 15,
	FIELD_TICK = 16,
	FIELD_SOUNDNAME = 17,
	FIELD_INPUT = 18,
	FIELD_FUNCTION = 19,
	FIELD_VMATRIX = 20,
	FIELD_VMATRIX_WORLDSPACE = 21,
	FIELD_MATRIX3X4_WORLDSPACE = 22,
	FIELD_INTERVAL = 23,
	FIELD_UNUSED = 24,
	FIELD_VECTOR2D = 25,
	FIELD_INTEGER64 = 26,
	FIELD_VECTOR4D = 27,
	FIELD_RESOURCE = 28,
	FIELD_TYPEUNKNOWN = 29,
	FIELD_CSTRING = 30,
	FIELD_HSCRIPT = 31,
	FIELD_VARIANT = 32,
	FIELD_UINT64 = 33,
	FIELD_FLOAT64 = 34,
	FIELD_POSITIVEINTEGER_OR_NULL = 35,
	FIELD_HSCRIPT_NEW_INSTANCE = 36,
	FIELD_UINT = 37,
	FIELD_UTLSTRINGTOKEN = 38,
	FIELD_QANGLE = 39,
	FIELD_NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR = 40,
	FIELD_HMATERIAL = 41,
	FIELD_HMODEL = 42,
	FIELD_NETWORK_QUANTIZED_VECTOR = 43,
	FIELD_NETWORK_QUANTIZED_FLOAT = 44,
	FIELD_DIRECTION_VECTOR_WORLDSPACE = 45,
	FIELD_QANGLE_WORLDSPACE = 46,
	FIELD_QUATERNION_WORLDSPACE = 47,
	FIELD_HSCRIPT_LIGHTBINDING = 48,
	FIELD_V8_VALUE = 49,
	FIELD_V8_OBJECT = 50,
	FIELD_V8_ARRAY = 51,
	FIELD_V8_CALLBACK_INFO = 52,
	FIELD_TYPECOUNT = 53,
};

enum class filter_t : unsigned long
{
	FILTER_AND = 0,
	FILTER_OR = 1,
};

enum class gamerules_roundstate_t : unsigned long
{
	GR_STATE_INIT = 0,
	GR_STATE_PREGAME = 1,
	GR_STATE_STARTGAME = 2,
	GR_STATE_PREROUND = 3,
	GR_STATE_RND_RUNNING = 4,
	GR_STATE_TEAM_WIN = 5,
	GR_STATE_RESTART = 6,
	GR_STATE_STALEMATE = 7,
	GR_STATE_GAME_OVER = 8,
	GR_NUM_ROUND_STATES = 9,
};

enum class gender_t : unsigned char
{
	GENDER_NONE = 0,
	GENDER_MALE = 1,
	GENDER_FEMALE = 2,
	GENDER_NAMVET = 3,
	GENDER_TEENGIRL = 4,
	GENDER_BIKER = 5,
	GENDER_MANAGER = 6,
	GENDER_GAMBLER = 7,
	GENDER_PRODUCER = 8,
	GENDER_COACH = 9,
	GENDER_MECHANIC = 10,
	GENDER_CEDA = 11,
	GENDER_CRAWLER = 12,
	GENDER_UNDISTRACTABLE = 13,
	GENDER_FALLEN = 14,
	GENDER_RIOT_CONTROL = 15,
	GENDER_CLOWN = 16,
	GENDER_JIMMY = 17,
	GENDER_HOSPITAL_PATIENT = 18,
	GENDER_BRIDE = 19,
};

enum class modifierfunction : unsigned long
{
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE = 0,
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT = 1,
	MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE = 2,
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL = 3,
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL = 4,
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE = 5,
	MODIFIER_PROPERTY_PROCATTACK_FEEDBACK = 6,
	MODIFIER_PROPERTY_PRE_ATTACK = 7,
	MODIFIER_PROPERTY_INVISIBILITY_LEVEL = 8,
	MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY = 9,
	MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT = 10,
	MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE = 11,
	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE = 12,
	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE = 13,
	MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE = 14,
	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE = 15,
	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN = 16,
	MODIFIER_PROPERTY_MOVESPEED_LIMIT = 17,
	MODIFIER_PROPERTY_MOVESPEED_MAX = 18,
	MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT = 19,
	MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT_POWER_TREADS = 20,
	MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT_SECONDARY = 21,
	MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT = 22,
	MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT = 23,
	MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT = 24,
	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE = 25,
	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION = 26,
	MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE = 27,
	MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE = 28,
	MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE = 29,
	MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE = 30,
	MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE = 31,
	MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT = 32,
	MODIFIER_PROPERTY_EVASION_CONSTANT = 33,
	MODIFIER_PROPERTY_AVOID_DAMAGE = 34,
	MODIFIER_PROPERTY_AVOID_SPELL = 35,
	MODIFIER_PROPERTY_MISS_PERCENTAGE = 36,
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS = 37,
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_ILLUSIONS = 38,
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE = 39,
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE = 40,
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS = 41,
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_ITEM_UNIQUE = 42,
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE = 43,
	MODIFIER_PROPERTY_BASE_MANA_REGEN = 44,
	MODIFIER_PROPERTY_MANA_REGEN_CONSTANT = 45,
	MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_UNIQUE = 46,
	MODIFIER_PROPERTY_MANA_REGEN_PERCENTAGE = 47,
	MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE = 48,
	MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT = 49,
	MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE = 50,
	MODIFIER_PROPERTY_HEALTH_BONUS = 51,
	MODIFIER_PROPERTY_MANA_BONUS = 52,
	MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS = 53,
	MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS = 54,
	MODIFIER_PROPERTY_EXTRA_MANA_BONUS = 55,
	MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE = 56,
	MODIFIER_PROPERTY_STATS_STRENGTH_BONUS = 57,
	MODIFIER_PROPERTY_STATS_AGILITY_BONUS = 58,
	MODIFIER_PROPERTY_STATS_INTELLECT_BONUS = 59,
	MODIFIER_PROPERTY_ATTACK_RANGE_BONUS = 60,
	MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS = 61,
	MODIFIER_PROPERTY_REINCARNATION = 62,
	MODIFIER_PROPERTY_RESPAWNTIME = 63,
	MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE = 64,
	MODIFIER_PROPERTY_RESPAWNTIME_STACKING = 65,
	MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE = 66,
	MODIFIER_PROPERTY_CASTTIME_PERCENTAGE = 67,
	MODIFIER_PROPERTY_MANACOST_PERCENTAGE = 68,
	MODIFIER_PROPERTY_DEATHGOLDCOST = 69,
	MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE = 70,
	MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK = 71,
	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR = 72,
	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK = 73,
	MODIFIER_PROPERTY_OVERRIDE_ANIMATION = 74,
	MODIFIER_PROPERTY_OVERRIDE_ANIMATION_WEIGHT = 75,
	MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE = 76,
	MODIFIER_PROPERTY_ABSORB_SPELL = 77,
	MODIFIER_PROPERTY_REFLECT_SPELL = 78,
	MODIFIER_PROPERTY_DISABLE_AUTOATTACK = 79,
	MODIFIER_PROPERTY_BONUS_DAY_VISION = 80,
	MODIFIER_PROPERTY_BONUS_NIGHT_VISION = 81,
	MODIFIER_PROPERTY_BONUS_NIGHT_VISION_UNIQUE = 82,
	MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE = 83,
	MODIFIER_PROPERTY_FIXED_DAY_VISION = 84,
	MODIFIER_PROPERTY_FIXED_NIGHT_VISION = 85,
	MODIFIER_PROPERTY_MIN_HEALTH = 86,
	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL = 87,
	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL = 88,
	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE = 89,
	MODIFIER_PROPERTY_IS_ILLUSION = 90,
	MODIFIER_PROPERTY_ILLUSION_LABEL = 91,
	MODIFIER_PROPERTY_SUPER_ILLUSION = 92,
	MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE = 93,
	MODIFIER_PROPERTY_DISABLE_HEALING = 94,
	MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL = 95,
	MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH = 96,
	MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER = 97,
	MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER = 98,
	MODIFIER_EVENT_ON_ATTACK_RECORD = 99,
	MODIFIER_EVENT_ON_ATTACK_START = 100,
	MODIFIER_EVENT_ON_ATTACK = 101,
	MODIFIER_EVENT_ON_ATTACK_LANDED = 102,
	MODIFIER_EVENT_ON_ATTACK_FAIL = 103,
	MODIFIER_EVENT_ON_ATTACK_ALLIED = 104,
	MODIFIER_EVENT_ON_PROJECTILE_DODGE = 105,
	MODIFIER_EVENT_ON_ORDER = 106,
	MODIFIER_EVENT_ON_UNIT_MOVED = 107,
	MODIFIER_EVENT_ON_ABILITY_START = 108,
	MODIFIER_EVENT_ON_ABILITY_EXECUTED = 109,
	MODIFIER_EVENT_ON_ABILITY_FULLY_CAST = 110,
	MODIFIER_EVENT_ON_BREAK_INVISIBILITY = 111,
	MODIFIER_EVENT_ON_ABILITY_END_CHANNEL = 112,
	MODIFIER_EVENT_ON_PROCESS_UPGRADE = 113,
	MODIFIER_EVENT_ON_REFRESH = 114,
	MODIFIER_EVENT_ON_TAKEDAMAGE = 115,
	MODIFIER_EVENT_ON_STATE_CHANGED = 116,
	MODIFIER_EVENT_ON_ORB_EFFECT = 117,
	MODIFIER_EVENT_ON_ATTACKED = 118,
	MODIFIER_EVENT_ON_DEATH = 119,
	MODIFIER_EVENT_ON_RESPAWN = 120,
	MODIFIER_EVENT_ON_SPENT_MANA = 121,
	MODIFIER_EVENT_ON_TELEPORTING = 122,
	MODIFIER_EVENT_ON_TELEPORTED = 123,
	MODIFIER_EVENT_ON_SET_LOCATION = 124,
	MODIFIER_EVENT_ON_HEALTH_GAINED = 125,
	MODIFIER_EVENT_ON_MANA_GAINED = 126,
	MODIFIER_EVENT_ON_TAKEDAMAGE_KILLCREDIT = 127,
	MODIFIER_EVENT_ON_HERO_KILLED = 128,
	MODIFIER_EVENT_ON_HEAL_RECEIVED = 129,
	MODIFIER_EVENT_ON_BUILDING_KILLED = 130,
	MODIFIER_EVENT_ON_MODEL_CHANGED = 131,
	MODIFIER_PROPERTY_TOOLTIP = 132,
	MODIFIER_PROPERTY_MODEL_CHANGE = 133,
	MODIFIER_PROPERTY_MODEL_SCALE = 134,
	MODIFIER_PROPERTY_IS_SCEPTER = 135,
	MODIFIER_PROPERTY_TRANSLATE_ACTIVITY_MODIFIERS = 136,
	MODIFIER_PROPERTY_TRANSLATE_ATTACK_SOUND = 137,
	MODIFIER_PROPERTY_LIFETIME_FRACTION = 138,
	MODIFIER_PROPERTY_PROVIDES_FOW_POSITION = 139,
	MODIFIER_PROPERTY_SPELLS_REQUIRE_HP = 140,
	MODIFIER_PROPERTY_FORCE_DRAW_MINIMAP = 141,
	MODIFIER_PROPERTY_DISABLE_TURNING = 142,
	MODIFIER_PROPERTY_IGNORE_CAST_ANGLE = 143,
	MODIFIER_PROPERTY_CHANGE_ABILITY_VALUE = 144,
	MODIFIER_PROPERTY_ABILITY_LAYOUT = 145,
	MODIFIER_EVENT_ON_DOMINATED = 146,
	MODIFIER_FUNCTION_LAST = 147,
	MODIFIER_FUNCTION_INVALID = 255,
};

enum class modifierstate : unsigned long
{
	MODIFIER_STATE_ROOTED = 0,
	MODIFIER_STATE_DISARMED = 1,
	MODIFIER_STATE_ATTACK_IMMUNE = 2,
	MODIFIER_STATE_SILENCED = 3,
	MODIFIER_STATE_MUTED = 4,
	MODIFIER_STATE_STUNNED = 5,
	MODIFIER_STATE_HEXED = 6,
	MODIFIER_STATE_INVISIBLE = 7,
	MODIFIER_STATE_INVULNERABLE = 8,
	MODIFIER_STATE_MAGIC_IMMUNE = 9,
	MODIFIER_STATE_PROVIDES_VISION = 10,
	MODIFIER_STATE_NIGHTMARED = 11,
	MODIFIER_STATE_BLOCK_DISABLED = 12,
	MODIFIER_STATE_EVADE_DISABLED = 13,
	MODIFIER_STATE_UNSELECTABLE = 14,
	MODIFIER_STATE_CANNOT_MISS = 15,
	MODIFIER_STATE_SPECIALLY_DENIABLE = 16,
	MODIFIER_STATE_FROZEN = 17,
	MODIFIER_STATE_COMMAND_RESTRICTED = 18,
	MODIFIER_STATE_NOT_ON_MINIMAP = 19,
	MODIFIER_STATE_NOT_ON_MINIMAP_FOR_ENEMIES = 20,
	MODIFIER_STATE_LOW_ATTACK_PRIORITY = 21,
	MODIFIER_STATE_NO_HEALTH_BAR = 22,
	MODIFIER_STATE_FLYING = 23,
	MODIFIER_STATE_NO_UNIT_COLLISION = 24,
	MODIFIER_STATE_NO_TEAM_MOVE_TO = 25,
	MODIFIER_STATE_NO_TEAM_SELECT = 26,
	MODIFIER_STATE_PASSIVES_DISABLED = 27,
	MODIFIER_STATE_DOMINATED = 28,
	MODIFIER_STATE_BLIND = 29,
	MODIFIER_STATE_OUT_OF_GAME = 30,
	MODIFIER_STATE_FAKE_ALLY = 31,
	MODIFIER_STATE_FLYING_FOR_PATHING_PURPOSES_ONLY = 32,
	MODIFIER_STATE_TRUESIGHT_IMMUNE = 33,
	MODIFIER_STATE_LAST = 34,
};

enum class mp_break_t : unsigned long
{
	MULTIPLAYER_BREAK_DEFAULT = 0,
	MULTIPLAYER_BREAK_SERVERSIDE = 1,
	MULTIPLAYER_BREAK_CLIENTSIDE = 2,
	MULTIPLAYER_BREAK_BOTH = 3,
};

enum class multiplayerBreak_t : unsigned long
{
	MULTIPLAYER_BREAK_SERVER = 0,
	MULTIPLAYER_BREAK_CLIENT = 1,
};

enum class navproperties_t : unsigned long
{
	NAV_IGNORE = 1,
};

enum class quest_hud_types_t : unsigned long
{
	QUEST_HUD_TYPE_DEFAULT = 0,
	QUEST_HUD_TYPE_GOLD = 1,
	QUEST_HUD_TYPE_ATTACK = 2,
	QUEST_HUD_TYPE_DEFEND = 3,
	QUEST_NUM_HUD_TYPES = 4,
};

enum class quest_text_replace_values_t : unsigned long
{
	QUEST_TEXT_REPLACE_VALUE_CURRENT_VALUE = 0,
	QUEST_TEXT_REPLACE_VALUE_TARGET_VALUE = 1,
	QUEST_TEXT_REPLACE_VALUE_ROUND = 2,
	QUEST_TEXT_REPLACE_VALUE_REWARD = 3,
	QUEST_NUM_TEXT_REPLACE_VALUES = 4,
};

enum class sound_states : unsigned long
{
	SS_NONE = 0,
	SS_SHUTDOWN = 1,
	SS_SHUTDOWN_WATER = 2,
	SS_START_WATER = 3,
	SS_START_IDLE = 4,
	SS_IDLE = 5,
	SS_GEAR_0 = 6,
	SS_GEAR_1 = 7,
	SS_GEAR_2 = 8,
	SS_GEAR_3 = 9,
	SS_GEAR_4 = 10,
	SS_SLOWDOWN = 11,
	SS_SLOWDOWN_HIGHSPEED = 12,
	SS_GEAR_0_RESUME = 13,
	SS_GEAR_1_RESUME = 14,
	SS_GEAR_2_RESUME = 15,
	SS_GEAR_3_RESUME = 16,
	SS_GEAR_4_RESUME = 17,
	SS_TURBO = 18,
	SS_REVERSE = 19,
	SS_NUM_STATES = 20,
};

enum class soundlevel_t : unsigned long
{
	SNDLVL_NONE = 0,
	SNDLVL_20dB = 20,
	SNDLVL_25dB = 25,
	SNDLVL_30dB = 30,
	SNDLVL_35dB = 35,
	SNDLVL_40dB = 40,
	SNDLVL_45dB = 45,
	SNDLVL_50dB = 50,
	SNDLVL_55dB = 55,
	SNDLVL_IDLE = 60,
	SNDLVL_60dB = 60,
	SNDLVL_65dB = 65,
	SNDLVL_STATIC = 66,
	SNDLVL_70dB = 70,
	SNDLVL_NORM = 75,
	SNDLVL_75dB = 75,
	SNDLVL_80dB = 80,
	SNDLVL_TALKING = 80,
	SNDLVL_85dB = 85,
	SNDLVL_90dB = 90,
	SNDLVL_95dB = 95,
	SNDLVL_100dB = 100,
	SNDLVL_105dB = 105,
	SNDLVL_110dB = 110,
	SNDLVL_120dB = 120,
	SNDLVL_130dB = 130,
	SNDLVL_GUNFIRE = 140,
	SNDLVL_140dB = 140,
	SNDLVL_150dB = 150,
	SNDLVL_180dB = 180,
};

enum class subquest_player_stat_types_t : unsigned long
{
	SUBQUEST_PLAYER_STAT_GOLD = 0,
	SUBQUEST_PLAYER_STAT_LEVEL = 1,
	SUBQUEST_PLAYER_STAT_LAST_HITS = 2,
	SUBQUEST_PLAYER_STAT_DENIES = 3,
	SUBQUEST_NUM_PLAYER_STATS = 4,
};

enum class subquest_text_replace_values_t : unsigned long
{
	SUBQUEST_TEXT_REPLACE_VALUE_CURRENT_VALUE = 0,
	SUBQUEST_TEXT_REPLACE_VALUE_TARGET_VALUE = 1,
	SUBQUEST_NUM_TEXT_REPLACE_VALUES = 2,
};

enum class vote_create_failed_t : unsigned long
{
	VOTE_FAILED_GENERIC = 0,
	VOTE_FAILED_TRANSITIONING_PLAYERS = 1,
	VOTE_FAILED_RATE_EXCEEDED = 2,
	VOTE_FAILED_YES_MUST_EXCEED_NO = 3,
	VOTE_FAILED_QUORUM_FAILURE = 4,
	VOTE_FAILED_ISSUE_DISABLED = 5,
	VOTE_FAILED_MAP_NOT_FOUND = 6,
	VOTE_FAILED_MAP_NAME_REQUIRED = 7,
	VOTE_FAILED_FAILED_RECENTLY = 8,
	VOTE_FAILED_TEAM_CANT_CALL = 9,
	VOTE_FAILED_WAITINGFORPLAYERS = 10,
	VOTE_FAILED_PLAYERNOTFOUND = 11,
	VOTE_FAILED_CANNOT_KICK_ADMIN = 12,
	VOTE_FAILED_SCRAMBLE_IN_PROGRESS = 13,
	VOTE_FAILED_SPECTATOR = 14,
};

